/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Cuadrillas;

import Datos.DReclamos;
import Datos.DServiciodelCliente;
import Datos.DSolicitud;
import Datos.DTrabajos;
import Datos.DTrabajosReclamos;
import Datos.DTrabajosSolicitud;
import Logica.ConexionSingleton;
import Logica.LClientes;
import Logica.LEstados;
import Logica.LTrabajos;
import Presentacion.Clientes.frmPrincipalMenu;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author josug
 */
public class frmRevisarReclamos extends javax.swing.JFrame {

    public int xx;
    public int xy;

    public static int control = 0;
    private LEstados es = new LEstados();
    public static String accion = "";
    /**
     * Valores para editar *
     */
    public static int idTrabajos;
    public static String id;
    public static int idTrabajosReclamos;
    public static int idReclamos;
    public static int idCliente;
    public static int idServicio;
    public static String nombres = "";
    public static String apellidos = "";
    public static String cedula = "";
    public static String nombreServicio = "";
    public static Date fechaReclamo;
    public static int idCuadrilla;
    public static String cuadrilla;
    public static int estado;
    public static String detalle;
    
    LTrabajos lt = new LTrabajos();
    public static String editar;
    public static String eliminar;

    /**
     * Creates new form frmPrincipalSolicitudesNuevo
     */
    public frmRevisarReclamos() {
        initComponents();
        mostrarReclamosPendientes("");
        ordenartamaños();
        this.setLocationRelativeTo(null);
        lblrevertir.setVisible(false);
        btnEditarSombra.setVisible(false);
        btnEditarSolicitud.setVisible(false);
        btnEliminarTrabajo.setVisible(false);
        btnEliminarSombra.setVisible(false);
    }

    public void ordenartamaños() {
        TableColumnModel Modelo = tblTrabajos.getColumnModel();
        Modelo.getColumn(0).setPreferredWidth(15);
        Modelo.getColumn(0).setResizable(false);
        Modelo.getColumn(1).setPreferredWidth(75);
        Modelo.getColumn(1).setResizable(false);
        Modelo.getColumn(2).setPreferredWidth(75);
        Modelo.getColumn(2).setResizable(false);
        Modelo.getColumn(3).setPreferredWidth(50);
        Modelo.getColumn(3).setResizable(false);
        Modelo.getColumn(4).setPreferredWidth(90);
        Modelo.getColumn(4).setResizable(false);
        Modelo.getColumn(5).setPreferredWidth(90);
        Modelo.getColumn(5).setResizable(false);
        Modelo.getColumn(6).setPreferredWidth(100);
        Modelo.getColumn(6).setResizable(false);
        Modelo.getColumn(7).setPreferredWidth(90);
        Modelo.getColumn(7).setResizable(false);
    }

  

    public void mostrarReclamosPendientes(String buscar) {
        try {
            DefaultTableModel miModelo;
            LTrabajos log = new LTrabajos();
            miModelo = log.mostrarReclamosPendientes(buscar);
            tblTrabajos.setModel(miModelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void mostrarReclamosAtendidos(String buscar) {
        try {
            DefaultTableModel miModelo;
            LTrabajos log = new LTrabajos();
            miModelo = log.mostrarReclamosAtendidos(buscar);
            tblTrabajos.setModel(miModelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAgregarCuadrilla = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        btnEditarSolicitud = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        btnEditarSombra = new javax.swing.JPanel();
        btnNuevaSolicitud5 = new javax.swing.JPanel();
        btnEliminarTrabajo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        btnEliminarSombra = new javax.swing.JPanel();
        btnVolver = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        btnNuevaSolicitud1 = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        btnNuevaSolicitud2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        btnReportes = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollTrabajos = new javax.swing.JScrollPane();
        tblTrabajos = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        btnMostrarServiciosActivos = new javax.swing.JPanel();
        lblAceptado = new javax.swing.JLabel();
        lblrevertir = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mover = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        btnMini = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarCuadrilla.setBackground(new java.awt.Color(102, 0, 0));
        btnAgregarCuadrilla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarCuadrilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarCuadrillaMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarCuadrillaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarCuadrillaMouseEntered(evt);
            }
        });
        btnAgregarCuadrilla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_plus_math_30px_1.png"))); // NOI18N
        btnAgregarCuadrilla.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 31, 36));
        btnAgregarCuadrilla.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 37, 246, 10));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("Atender Reclamo");
        btnAgregarCuadrilla.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel2.add(btnAgregarCuadrilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 240, 50));

        btnEditarSolicitud.setBackground(new java.awt.Color(102, 0, 0));
        btnEditarSolicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditarSolicitud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditarSolicitud.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnEditarSolicitudFocusGained(evt);
            }
        });
        btnEditarSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarSolicitudMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditarSolicitudMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarSolicitudMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarSolicitudMouseEntered(evt);
            }
        });
        btnEditarSolicitud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_edit_30px.png"))); // NOI18N
        btnEditarSolicitud.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 31, 36));
        btnEditarSolicitud.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 37, 171, 10));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("Editar Reclamo");
        btnEditarSolicitud.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 11, -1, -1));

        jPanel2.add(btnEditarSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 240, 50));

        btnEditarSombra.setBackground(new java.awt.Color(0, 0, 0));
        btnEditarSombra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditarSombra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditarSombra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnEditarSombraFocusGained(evt);
            }
        });
        btnEditarSombra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarSombraMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditarSombraMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarSombraMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarSombraMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnEditarSombraLayout = new javax.swing.GroupLayout(btnEditarSombra);
        btnEditarSombra.setLayout(btnEditarSombraLayout);
        btnEditarSombraLayout.setHorizontalGroup(
            btnEditarSombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnEditarSombraLayout.setVerticalGroup(
            btnEditarSombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnEditarSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 240, 50));

        btnNuevaSolicitud5.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaSolicitud5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitud5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitud5FocusGained(evt);
            }
        });
        btnNuevaSolicitud5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud5MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitud5Layout = new javax.swing.GroupLayout(btnNuevaSolicitud5);
        btnNuevaSolicitud5.setLayout(btnNuevaSolicitud5Layout);
        btnNuevaSolicitud5Layout.setHorizontalGroup(
            btnNuevaSolicitud5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnNuevaSolicitud5Layout.setVerticalGroup(
            btnNuevaSolicitud5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnNuevaSolicitud5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 240, 50));

        btnEliminarTrabajo.setBackground(new java.awt.Color(102, 0, 0));
        btnEliminarTrabajo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarTrabajo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminarTrabajo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnEliminarTrabajoFocusGained(evt);
            }
        });
        btnEliminarTrabajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarTrabajoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEliminarTrabajoMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarTrabajoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarTrabajoMouseEntered(evt);
            }
        });
        btnEliminarTrabajo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_trash_30px.png"))); // NOI18N
        btnEliminarTrabajo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 31, 36));
        btnEliminarTrabajo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 37, 171, 10));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("Eliminar Reclamo");
        btnEliminarTrabajo.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 11, -1, -1));

        jPanel2.add(btnEliminarTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 240, 50));

        btnEliminarSombra.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminarSombra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarSombra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminarSombra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnEliminarSombraFocusGained(evt);
            }
        });
        btnEliminarSombra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarSombraMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEliminarSombraMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarSombraMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarSombraMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnEliminarSombraLayout = new javax.swing.GroupLayout(btnEliminarSombra);
        btnEliminarSombra.setLayout(btnEliminarSombraLayout);
        btnEliminarSombraLayout.setHorizontalGroup(
            btnEliminarSombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnEliminarSombraLayout.setVerticalGroup(
            btnEliminarSombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnEliminarSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 240, 50));

        btnVolver.setBackground(new java.awt.Color(102, 0, 0));
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVolverMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
        });
        btnVolver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_back_30px.png"))); // NOI18N
        btnVolver.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 31, 36));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Volver al Menu");
        btnVolver.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 11, -1, -1));
        btnVolver.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 37, 170, 10));

        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 240, 50));

        btnNuevaSolicitud1.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaSolicitud1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitud1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitud1FocusGained(evt);
            }
        });
        btnNuevaSolicitud1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud1MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitud1Layout = new javax.swing.GroupLayout(btnNuevaSolicitud1);
        btnNuevaSolicitud1.setLayout(btnNuevaSolicitud1Layout);
        btnNuevaSolicitud1Layout.setHorizontalGroup(
            btnNuevaSolicitud1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnNuevaSolicitud1Layout.setVerticalGroup(
            btnNuevaSolicitud1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnNuevaSolicitud1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 240, 50));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 40, 20));
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 40, 20));
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 40, 10));

        jLabel20.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("SERVINET");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, -1, -1));

        jLabel19.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("REVISAR RECLAMOS");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 220, 50));

        jLabel17.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("JOTZPOT");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel21.setFont(new java.awt.Font("Bauhaus 93", 1, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("INTERNET");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 30, 50, -1));

        btnActualizar.setBackground(new java.awt.Color(102, 0, 0));
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnActualizarMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarMouseEntered(evt);
            }
        });
        btnActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_back_30px.png"))); // NOI18N
        btnActualizar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 31, 36));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Actualizar");
        btnActualizar.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 11, -1, -1));
        btnActualizar.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 37, 170, 10));

        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 240, 50));

        btnNuevaSolicitud2.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaSolicitud2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitud2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitud2FocusGained(evt);
            }
        });
        btnNuevaSolicitud2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud2MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud2MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitud2Layout = new javax.swing.GroupLayout(btnNuevaSolicitud2);
        btnNuevaSolicitud2.setLayout(btnNuevaSolicitud2Layout);
        btnNuevaSolicitud2Layout.setHorizontalGroup(
            btnNuevaSolicitud2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnNuevaSolicitud2Layout.setVerticalGroup(
            btnNuevaSolicitud2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnNuevaSolicitud2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 240, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 610));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 32, 160, -1));

        btnReportes.setBackground(new java.awt.Color(102, 0, 0));
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnReportesMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportesMouseEntered(evt);
            }
        });
        btnReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_print_30px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        btnReportes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 30, 38));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Imprimir Reporte");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel22MousePressed(evt);
            }
        });
        btnReportes.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel3.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 170, 40));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 170, 40));

        btnBuscar.setBackground(new java.awt.Color(102, 0, 0));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
        });
        btnBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_search_30px_1.png"))); // NOI18N
        btnBuscar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jPanel3.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 50, 50));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 50, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 920, 80));

        jScrollTrabajos.setBorder(null);

        tblTrabajos.setAutoCreateRowSorter(true);
        tblTrabajos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblTrabajos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblTrabajos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblTrabajos.setGridColor(new java.awt.Color(255, 255, 255));
        tblTrabajos.setRowHeight(25);
        tblTrabajos.setSelectionBackground(new java.awt.Color(153, 0, 0));
        tblTrabajos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTrabajosMouseClicked(evt);
            }
        });
        jScrollTrabajos.setViewportView(tblTrabajos);

        jPanel1.add(jScrollTrabajos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 780, 390));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 10, 200));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 10, 200));

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 10, 200));

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 10, 200));

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 10, 200));

        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 10, 200));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 140, 110, 470));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrarServiciosActivos.setBackground(new java.awt.Color(102, 0, 0));
        btnMostrarServiciosActivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMostrarServiciosActivosMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarServiciosActivosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarServiciosActivosMouseEntered(evt);
            }
        });
        btnMostrarServiciosActivos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAceptado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAceptado.setForeground(new java.awt.Color(204, 204, 204));
        lblAceptado.setText("ESTADO ACEPTADO");
        btnMostrarServiciosActivos.add(lblAceptado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblrevertir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblrevertir.setForeground(new java.awt.Color(204, 204, 204));
        lblrevertir.setText("REVERTIR");
        btnMostrarServiciosActivos.add(lblrevertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel10.add(btnMostrarServiciosActivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 140, 30));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setEnabled(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 140, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MOSTRAR:");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 830, 60));

        mover.setBackground(new java.awt.Color(204, 204, 204));
        mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moverMouseDragged(evt);
            }
        });
        mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moverMousePressed(evt);
            }
        });
        mover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(102, 0, 0));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px.png"))); // NOI18N
        btnSalir.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 20, 20));

        mover.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 30, 30));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        mover.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 20, 30, 30));

        btnMini.setBackground(new java.awt.Color(102, 0, 0));
        btnMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMiniMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMiniMouseEntered(evt);
            }
        });
        btnMini.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_minimize_window_20px.png"))); // NOI18N
        btnMini.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 20, 20));

        mover.add(btnMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 30, 30));

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        mover.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, 30, 30));

        jPanel1.add(mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1210, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCuadrillaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarCuadrillaMousePressed
        if (tblTrabajos.getSelectedRows().length > 0) {
            frmValoresAtenderReclamos form = new frmValoresAtenderReclamos();
            accion = "cargar";
            form.cargarValores();
            form.setVisible(true);
            form.toFront();
        } else {
            JOptionPane.showMessageDialog(null, "Se debe de seleccionar un registro");
        }
    }//GEN-LAST:event_btnAgregarCuadrillaMousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed

    }//GEN-LAST:event_jPanel1MousePressed

    private void tblTrabajosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTrabajosMouseClicked
        int fila = tblTrabajos.rowAtPoint(evt.getPoint());
        idTrabajosReclamos = Integer.parseInt(tblTrabajos.getValueAt(fila, 0).toString());
        id = tblTrabajos.getValueAt(fila, 0).toString();
        idTrabajos = lt.traerIdTrabajosConReclamos(idTrabajosReclamos);
        idReclamos = lt.traerIdReclamos(idTrabajosReclamos);
        detalle = lt.traerDetalle(idReclamos);
        idCliente = lt.traerIdClienteConReclamos(idReclamos);
        nombres = tblTrabajos.getValueAt(fila, 1).toString();
        apellidos = tblTrabajos.getValueAt(fila, 2).toString();
        cedula = tblTrabajos.getValueAt(fila, 3).toString();
        fechaReclamo = Date.valueOf(tblTrabajos.getValueAt(fila, 4).toString());
        int idDetalle = lt.traerIdDetalleServicio(idCliente);
        idServicio = lt.traerIdServicio(idDetalle);
        nombreServicio = tblTrabajos.getValueAt(fila, 5).toString();
        cuadrilla = tblTrabajos.getValueAt(fila, 6).toString();
        idCuadrilla = lt.traerIdCuadrilla(cuadrilla);
    }//GEN-LAST:event_tblTrabajosMouseClicked

    private void btnEditarSolicitudFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnEditarSolicitudFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarSolicitudFocusGained

    private void btnEditarSolicitudMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarSolicitudMouseEntered
        setColor(btnEditarSolicitud);
    }//GEN-LAST:event_btnEditarSolicitudMouseEntered

    private void btnEditarSolicitudMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarSolicitudMouseExited
        resetColor(btnEditarSolicitud);
    }//GEN-LAST:event_btnEditarSolicitudMouseExited

    private void btnEditarSolicitudMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarSolicitudMousePressed
        editar = "si";
        frmValoresAtenderReclamos form = new frmValoresAtenderReclamos();
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_btnEditarSolicitudMousePressed

    private void btnEditarSolicitudMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarSolicitudMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarSolicitudMouseReleased

    private void btnEditarSombraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnEditarSombraFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarSombraFocusGained

    private void btnEditarSombraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarSombraMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarSombraMouseEntered

    private void btnEditarSombraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarSombraMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarSombraMouseExited

    private void btnEditarSombraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarSombraMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarSombraMousePressed

    private void btnEditarSombraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarSombraMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarSombraMouseReleased

    private void btnNuevaSolicitud5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud5FocusGained

    private void btnNuevaSolicitud5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud5MouseEntered

    private void btnNuevaSolicitud5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud5MouseExited

    private void btnNuevaSolicitud5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud5MousePressed

    private void btnNuevaSolicitud5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud5MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud5MouseReleased

    private void btnEliminarTrabajoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnEliminarTrabajoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarTrabajoFocusGained

    private void btnEliminarTrabajoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarTrabajoMouseEntered
        setColor(btnEliminarTrabajo);
    }//GEN-LAST:event_btnEliminarTrabajoMouseEntered

    private void btnEliminarTrabajoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarTrabajoMouseExited
        resetColor(btnEliminarTrabajo);
    }//GEN-LAST:event_btnEliminarTrabajoMouseExited

    private void btnEliminarTrabajoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarTrabajoMousePressed
        eliminar = "si";
        if(!id.equals("")){
            int mensaje = JOptionPane.showConfirmDialog(rootPane, "¿Desea eliminar el trabajo?");
            if(mensaje == 0){
                DTrabajos dt = new DTrabajos();
                DTrabajosReclamos dtr = new DTrabajosReclamos();
                DReclamos dr = new DReclamos();
                LClientes fun = new LClientes();
                
                dt.setIdTrabajos(idTrabajos);
                dtr.setIdTrabajosReclamos(idTrabajosReclamos);
                dr.setIdReclamos(idReclamos);
                fun.eliminarReclamos(dtr, dt, dr);
            }
        }
    }//GEN-LAST:event_btnEliminarTrabajoMousePressed

    private void btnEliminarTrabajoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarTrabajoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarTrabajoMouseReleased

    private void btnEliminarSombraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnEliminarSombraFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarSombraFocusGained

    private void btnEliminarSombraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarSombraMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarSombraMouseEntered

    private void btnEliminarSombraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarSombraMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarSombraMouseExited

    private void btnEliminarSombraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarSombraMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarSombraMousePressed

    private void btnEliminarSombraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarSombraMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarSombraMouseReleased

    private void btnVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMousePressed
        frmMenuCuadrillas form = new frmMenuCuadrillas();
        form.setVisible(true);
        form.toFront();
        this.dispose();
    }//GEN-LAST:event_btnVolverMousePressed

    private void btnNuevaSolicitud1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1FocusGained

    private void btnNuevaSolicitud1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1MouseEntered

    private void btnNuevaSolicitud1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1MouseExited

    private void btnNuevaSolicitud1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1MousePressed

    private void btnNuevaSolicitud1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1MouseReleased

    private void btnMostrarServiciosActivosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarServiciosActivosMousePressed
        if (lblAceptado.isVisible()) {
            lblAceptado.setVisible(false);
            lblrevertir.setVisible(true);
            mostrarReclamosAtendidos("");
            ordenartamaños();
            btnEditarSombra.setVisible(true);
            btnEditarSolicitud.setVisible(true);
            btnEliminarSombra.setVisible(true);
            btnEliminarTrabajo.setVisible(true);
        } else {
            lblAceptado.setVisible(true);
            lblrevertir.setVisible(false);
            mostrarReclamosPendientes("");
            ordenartamaños();
            btnEditarSombra.setVisible(false);
            btnEditarSolicitud.setVisible(false);
            btnEliminarSombra.setVisible(false);
            btnEliminarTrabajo.setVisible(false);
        }
    }//GEN-LAST:event_btnMostrarServiciosActivosMousePressed

    private void btnReportesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMousePressed
        frmElegirReporteReclamos form = new frmElegirReporteReclamos();
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_btnReportesMousePressed

    private void jLabel22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MousePressed
        frmElegirReporteReclamos form = new frmElegirReporteReclamos();
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_jLabel22MousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        //frmElegirReporteSolicitudes form = new frmElegirReporteSolicitudes();
        //form.setVisible(true);
        //form.toFront();
    }//GEN-LAST:event_jLabel7MousePressed

    private void btnActualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMousePressed
        Connection cn = ConexionSingleton.getConnection();
        if(lblAceptado.isVisible()){
            mostrarReclamosPendientes("");
            ordenartamaños();
        }else{
            mostrarReclamosAtendidos("");
            ordenartamaños();
        }
    }//GEN-LAST:event_btnActualizarMousePressed

    private void btnNuevaSolicitud2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud2FocusGained

    private void btnNuevaSolicitud2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud2MousePressed

    private void btnNuevaSolicitud2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud2MouseReleased

    private void btnNuevaSolicitud2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud2MouseExited

    private void btnNuevaSolicitud2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud2MouseEntered

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        if ("Abierto".equals(estado)) {
            JOptionPane.showMessageDialog(null, "La caja está abierta");
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirMousePressed

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        resetColor(btnSalir);
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        setColor(btnSalir);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnMiniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiniMouseExited
        resetColor(btnMini);
    }//GEN-LAST:event_btnMiniMouseExited

    private void btnMiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiniMouseEntered
        setColor(btnMini);
    }//GEN-LAST:event_btnMiniMouseEntered

    private void moverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_moverMouseDragged

    private void moverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_moverMousePressed

    private void btnAgregarCuadrillaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarCuadrillaMouseEntered
        setColor(btnAgregarCuadrilla);
    }//GEN-LAST:event_btnAgregarCuadrillaMouseEntered

    private void btnAgregarCuadrillaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarCuadrillaMouseExited
        resetColor(btnAgregarCuadrilla);
    }//GEN-LAST:event_btnAgregarCuadrillaMouseExited

    private void btnActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseEntered
        setColor(btnActualizar);
    }//GEN-LAST:event_btnActualizarMouseEntered

    private void btnActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseExited
        resetColor(btnActualizar);
    }//GEN-LAST:event_btnActualizarMouseExited

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        setColor(btnVolver);
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        resetColor(btnVolver);
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnMostrarServiciosActivosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarServiciosActivosMouseEntered
        setColor(btnMostrarServiciosActivos);
    }//GEN-LAST:event_btnMostrarServiciosActivosMouseEntered

    private void btnMostrarServiciosActivosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarServiciosActivosMouseExited
        resetColor(btnMostrarServiciosActivos);
    }//GEN-LAST:event_btnMostrarServiciosActivosMouseExited

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        setColor(btnBuscar);
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        resetColor(btnBuscar);
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseEntered
        setColor(btnReportes);
    }//GEN-LAST:event_btnReportesMouseEntered

    private void btnReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseExited
        resetColor(btnReportes);
    }//GEN-LAST:event_btnReportesMouseExited

    void setColor(JPanel panel) {
        panel.setBackground(new Color(51, 0, 0));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(102, 0, 0));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRevisarReclamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRevisarReclamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRevisarReclamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRevisarReclamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRevisarReclamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnActualizar;
    private javax.swing.JPanel btnAgregarCuadrilla;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnEditarSolicitud;
    private javax.swing.JPanel btnEditarSombra;
    private javax.swing.JPanel btnEliminarSombra;
    private javax.swing.JPanel btnEliminarTrabajo;
    private javax.swing.JPanel btnMini;
    private javax.swing.JPanel btnMostrarServiciosActivos;
    private javax.swing.JPanel btnNuevaSolicitud1;
    private javax.swing.JPanel btnNuevaSolicitud2;
    private javax.swing.JPanel btnNuevaSolicitud5;
    private javax.swing.JPanel btnReportes;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JPanel btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollTrabajos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAceptado;
    private javax.swing.JLabel lblrevertir;
    private javax.swing.JPanel mover;
    private javax.swing.JTable tblTrabajos;
    // End of variables declaration//GEN-END:variables
}
