/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Cuadrillas;

import Presentacion.Clientes.*;
import Datos.DClientes;
import Datos.DPersona;
import Datos.DReclamos;
import Datos.DServiciodelCliente;
import Datos.DSolicitud;
import Datos.DTrabajos;
import Datos.DTrabajosReclamos;
import Datos.DTrabajosSolicitud;
import Logica.LClientes;
import Logica.LEstados;
import Logica.LSolicitud;
import Logica.LTrabajos;
import Presentacion.Mantenimiento.frmVistaCuadrillaNuevo;
import Presentacion.Mantenimiento.frmVistaDireccionNuevo;
import Presentacion.Mantenimiento.frmVistaServicioNuevo;
import Presentacion.Mantenimiento.frmVistaZonaNuevo;
import java.awt.Color;
import java.sql.Date;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author josug
 */
public class frmValoresAtenderReclamos extends javax.swing.JFrame {

    public static int control = 0;
    private LEstados es = new LEstados();
    Calendar fecha_actual = new GregorianCalendar();

    String accion = null;

    LClientes lc = new LClientes();

    /**
     * Creates new form frmValoresSolicitudNuevo
     */
    public frmValoresAtenderReclamos() {
        initComponents();
        this.setLocationRelativeTo(null);
        limpiar();
        cargarValores();
        txtNombres.setEditable(false);
        txtApellidos.setEditable(false);
        txtCedula.setEditable(false);
        txtDetalle.requestFocus();
        txtIdCliente.setEditable(false);
        txtIdCuadrilla.setEditable(false);
        txtIdServicio.setEditable(false);
        txtServicio.setEditable(false);
        txtCuadrilla.setEditable(false);
        jdFechaSolicitud.setEnabled(false);
    }

    void limpiar() {
        txtIdCliente.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtIdCuadrilla.setText("");
        txtIdServicio.setText("");
        txtCuadrilla.setText("");
        txtServicio.setText("");
        jdFechaSolicitud.setDate(new Date(0, 0, 0));

    }

    public void cargarValores() {
        frmRevisarReclamos form = new frmRevisarReclamos();
        txtIdServicio.setText(String.valueOf(form.idServicio));
        txtIdCliente.setText(String.valueOf(form.idCliente));
        txtIdCuadrilla.setText(String.valueOf(form.idCuadrilla));
        txtNombres.setText(form.nombres);
        txtApellidos.setText(form.apellidos);
        txtCedula.setText(form.cedula);
        txtServicio.setText(form.nombreServicio);
        txtCuadrilla.setText(form.cuadrilla);
        jdFechaSolicitud.setDate(form.fechaReclamo);
        txtDetalle.setText(form.detalle);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtCuadrilla = new javax.swing.JTextField();
        txtIdCuadrilla = new javax.swing.JTextField();
        txtIdServicio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtServicio = new javax.swing.JTextField();
        jdFechaSolicitud = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        btnBuscarCuadrilla = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnGuardar2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnGuardar3 = new javax.swing.JPanel();
        jSeparator30 = new javax.swing.JSeparator();
        jSeparator28 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator29 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalle = new javax.swing.JTextArea();
        bar = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 541, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombres:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, -1, -1));
        jPanel2.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 200, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellidos:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, -1, -1));
        jPanel2.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, 200, -1));
        jPanel2.add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 53, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID Cliente:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));
        jPanel2.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cedula:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 230, 250));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txtCuadrilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 230, -1));
        jPanel3.add(txtIdCuadrilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 53, -1));
        jPanel3.add(txtIdServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 53, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tipo de Solicitud:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServicioActionPerformed(evt);
            }
        });
        jPanel3.add(txtServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 230, -1));

        jdFechaSolicitud.setDateFormatString("yyyy/MM/dd");
        jPanel3.add(jdFechaSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Elegir Cuadrilla:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        btnBuscarCuadrilla.setBackground(new java.awt.Color(102, 0, 0));
        btnBuscarCuadrilla.setPreferredSize(new java.awt.Dimension(40, 40));
        btnBuscarCuadrilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarCuadrillaMousePressed(evt);
            }
        });
        btnBuscarCuadrilla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_search_20px.png"))); // NOI18N
        btnBuscarCuadrilla.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 20));

        jPanel3.add(btnBuscarCuadrilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 40, 40));

        btnGuardar2.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardar2.setEnabled(false);

        javax.swing.GroupLayout btnGuardar2Layout = new javax.swing.GroupLayout(btnGuardar2);
        btnGuardar2.setLayout(btnGuardar2Layout);
        btnGuardar2Layout.setHorizontalGroup(
            btnGuardar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        btnGuardar2Layout.setVerticalGroup(
            btnGuardar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(btnGuardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Fecha de Solicitud:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 400, 250));

        btnGuardar.setBackground(new java.awt.Color(102, 0, 0));
        btnGuardar.setPreferredSize(new java.awt.Dimension(50, 50));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuardarMousePressed(evt);
            }
        });
        btnGuardar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_save_30px.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(25, 25));
        btnGuardar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 50, 50));

        btnGuardar1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout btnGuardar1Layout = new javax.swing.GroupLayout(btnGuardar1);
        btnGuardar1.setLayout(btnGuardar1Layout);
        btnGuardar1Layout.setHorizontalGroup(
            btnGuardar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        btnGuardar1Layout.setVerticalGroup(
            btnGuardar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, -1, 50));

        btnSalir.setBackground(new java.awt.Color(102, 0, 0));
        btnSalir.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_delete_30px.png"))); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(25, 25));
        btnSalir.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 50, 50));

        btnGuardar3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout btnGuardar3Layout = new javax.swing.GroupLayout(btnGuardar3);
        btnGuardar3.setLayout(btnGuardar3Layout);
        btnGuardar3Layout.setHorizontalGroup(
            btnGuardar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        btnGuardar3Layout.setVerticalGroup(
            btnGuardar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnGuardar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 50, 50));

        jSeparator30.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 460));
        jPanel1.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 270, 20));

        jSeparator27.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 20, 30));
        jPanel1.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 410, 20));

        jSeparator29.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 20, 350));
        jPanel1.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 140, 10));

        jSeparator25.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 20, 50));
        jPanel1.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 550, 20));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Detalle:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtDetalle.setColumns(20);
        txtDetalle.setRows(5);
        jScrollPane1.setViewportView(txtDetalle);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 500, 90));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 520, 140));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 750, 510));

        bar.setBackground(new java.awt.Color(204, 204, 204));
        bar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator5.setBackground(new java.awt.Color(204, 204, 204));
        bar.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 200, 20));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("INSERTE LA CUADRILLA PARA EL TRABAJO");
        bar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SERVINET");
        bar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jPanel4.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 750, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        this.dispose();
    }//GEN-LAST:event_btnSalirMousePressed

    private void btnGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMousePressed
        if ("".equals(txtCuadrilla.getText()) || "".equals(txtIdCuadrilla.getText())) {
            txtCuadrilla.setBackground(Color.red);
            txtIdCuadrilla.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Se necesita registrar la cuadrilla");
        } else {
            JOptionPane.showMessageDialog(null, "Se han registrado los datos");

            DTrabajosReclamos dtr = new DTrabajosReclamos();
            DTrabajos dt = new DTrabajos();
            DReclamos dr = new DReclamos();
            LClientes fun = new LClientes();

            dtr.setCuadrillasId(Integer.parseInt(txtIdCuadrilla.getText()));
            int idCliente = Integer.parseInt(txtIdCliente.getText());
            int idReclamos = lc.traerIdReclamos(idCliente);
            dr.setIdReclamos(idReclamos);
            int idTrabajosReclamos = lc.traerIdTrabajosReclamos(idReclamos);
            dtr.setIdTrabajosReclamos(idTrabajosReclamos);
            dt.setIdTrabajos(idTrabajosReclamos);
            fun.enviarReclamos(dtr, dt, dr);

            this.dispose();
        }
    }//GEN-LAST:event_btnGuardarMousePressed

    private void btnBuscarCuadrillaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCuadrillaMousePressed
        txtCuadrilla.setBackground(Color.WHITE);
        txtIdCuadrilla.setBackground(Color.WHITE);
        control = 3;
        frmVistaCuadrillaNuevo form = new frmVistaCuadrillaNuevo();
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_btnBuscarCuadrillaMousePressed

    private void txtServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmValoresAtenderReclamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmValoresAtenderReclamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmValoresAtenderReclamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmValoresAtenderReclamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmValoresAtenderReclamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnBuscarCuadrilla;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JPanel btnGuardar1;
    private javax.swing.JPanel btnGuardar2;
    private javax.swing.JPanel btnGuardar3;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator5;
    private com.toedter.calendar.JDateChooser jdFechaSolicitud;
    public static javax.swing.JTextField txtApellidos;
    public static javax.swing.JTextField txtCedula;
    public static javax.swing.JTextField txtCuadrilla;
    private javax.swing.JTextArea txtDetalle;
    public static javax.swing.JTextField txtIdCliente;
    public static javax.swing.JTextField txtIdCuadrilla;
    public static javax.swing.JTextField txtIdServicio;
    public static javax.swing.JTextField txtNombres;
    public static javax.swing.JTextField txtServicio;
    // End of variables declaration//GEN-END:variables
}
