/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.DEstadoServicio;
import Datos.DPersona;
import Datos.DServicios;
import Datos.DTipoServicio;
import Datos.DTipoUsuario;
import Datos.DUsuarios;
import Datos.guardarDatos;
import Logica.LServicios;
import Logica.LTipoUsuario;
import Logica.LUsuarios;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josug
 */
public class frmServicios extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmUsuario
     */
    String accion = null;
    
    public frmServicios() {
        initComponents();
        mostrarBuscar("");
        txtId.setVisible(false);
        txtNombre.setVisible(false);
        txtVelocidad.setVisible(false);
        txtPrecio.setVisible(false);
        txtDescripción.setVisible(false);
        cmbEstado.setVisible(false);
        cmbTipoServicio.setVisible(false);
        
        btnGuardar.setVisible(false);
        btnCancelar.setVisible(false);
        
        btnInternet.setVisible(false);
        btnTelefonía.setVisible(false);
        
        lblId.setVisible(false);
        lblNombre.setVisible(false);
        lblPrecio.setVisible(false);
        lblVelocidad.setVisible(false);
        lblDescripcion.setVisible(false);
        lblTipoServicio.setVisible(false);
        lblEstadoServicio.setVisible(false);
        
        
    }
    
    public void mostrarBuscar(String buscar){
        try {
            DefaultTableModel miModelo;
            LServicios log = new LServicios();
            miModelo = log.mostrarServicios(buscar);
            tblUsuarios.setModel(miModelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void modificar(){
        /*txtId.setVisible(true);
        txtNombre.setVisible(true);
        txtVelocidad.setVisible(true);
        txtVelocidad.setEnabled(true);
        txtPrecio.setVisible(true);
        txtDescripción.setVisible(true);
        cmbEstado.setVisible(true);
        cmbTipoServicio.setVisible(true);
        
        btnGuardar.setVisible(true);
        btnCancelar.setVisible(true);
        
        lblId.setVisible(true);
        lblNombre.setVisible(true);
        lblVelocidad.setVisible(true);
        lblPrecio.setVisible(true);
        lblDescripcion.setVisible(true);
        lblVelocidad.setVisible(true);
        lblEstadoServicio.setVisible(true);
        
        btnAgregar.setVisible(false);
        btnEditar.setVisible(false);
        btnCancelarForm.setVisible(false);
        btnEliminar.setVisible(false);*/
        
        btnInternet.setVisible(true);
        btnTelefonía.setVisible(true);
        btnCancelar.setVisible(true);
        
        btnAgregar.setVisible(false);
        btnEditar.setVisible(false);
        btnCancelarForm.setVisible(false);
        btnEliminar.setVisible(false);
    }
    
    public void mostrarBotones(){
        txtId.setVisible(false);
        txtNombre.setVisible(false);
        txtVelocidad.setVisible(false);
        txtPrecio.setVisible(false);
        txtDescripción.setVisible(false);
        cmbEstado.setVisible(false);
        cmbTipoServicio.setVisible(false);
        
        btnGuardar.setVisible(false);
        btnCancelar.setVisible(false);
        
        lblId.setVisible(false);
        lblNombre.setVisible(false);
        lblVelocidad.setVisible(false);
        lblPrecio.setVisible(false);
        lblDescripcion.setVisible(false);
        lblTipoServicio.setVisible(false);
        lblEstadoServicio.setVisible(false);
        
        btnAgregar.setVisible(true);
        btnEditar.setVisible(true);
        btnCancelarForm.setVisible(true);
        btnEliminar.setVisible(true);
        btnInternet.setVisible(false);
        btnTelefonía.setVisible(false);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelarForm = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtVelocidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtDescripción = new javax.swing.JTextField();
        lblEstadoServicio = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblVelocidad = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        cmbTipoServicio = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblTipoServicio = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        btnInternet = new javax.swing.JButton();
        btnTelefonía = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        buscar = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 104, 88));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 104, 88));

        btnCancelarForm.setText("Cancelar");
        jPanel1.add(btnCancelarForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 104, 88));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 104, 30));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 250, -1));
        jPanel1.add(txtVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 250, -1));
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 250, -1));
        jPanel1.add(txtDescripción, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 250, -1));

        lblEstadoServicio.setText("Estado del Servicio:");
        jPanel1.add(lblEstadoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        lblId.setText("ID:");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        lblNombre.setText("Nombre:");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lblVelocidad.setText("Velocidad de Conexión:");
        jPanel1.add(lblVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        lblDescripcion.setText("Descripción:");
        jPanel1.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        cmbTipoServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija el Tipo de Servicio", "Internet ADSL", "Internet Fibra Óptica", "Teléfono Fijo" }));
        jPanel1.add(cmbTipoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 250, 20));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 104, 30));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 104, 88));

        lblTipoServicio.setText("Tipo de Servicio:");
        jPanel1.add(lblTipoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija el Estado del Servicio", "Activo", "Inactivo" }));
        jPanel1.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 250, 20));

        btnInternet.setText("Internet");
        btnInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInternetActionPerformed(evt);
            }
        });
        jPanel1.add(btnInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 104, 88));

        btnTelefonía.setText("Telefonía");
        btnTelefonía.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelefoníaActionPerformed(evt);
            }
        });
        jPanel1.add(btnTelefonía, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 104, 88));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 250, -1));

        lblPrecio.setText("Precio:");
        jPanel1.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 290, 490));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        jButton5.setText("Buscar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 11, 690, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        btnInternet.setVisible(true);
        btnTelefonía.setVisible(true);
        btnCancelar.setVisible(true);
        
        btnAgregar.setVisible(false);
        btnEditar.setVisible(false);
        btnCancelarForm.setVisible(false);
        btnEliminar.setVisible(false);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        int fila = tblUsuarios.rowAtPoint(evt.getPoint());
        txtId.setText(tblUsuarios.getValueAt(fila, 0).toString());
        txtNombre.setText(tblUsuarios.getValueAt(fila, 1).toString());
        txtVelocidad.setText(tblUsuarios.getValueAt(fila, 2).toString());
        txtPrecio.setText(tblUsuarios.getValueAt(fila, 3).toString());
        txtDescripción.setText(tblUsuarios.getValueAt(fila, 4).toString());
        cmbTipoServicio.setSelectedItem(tblUsuarios.getValueAt(fila, 5).toString());
        cmbEstado.setSelectedItem(tblUsuarios.getValueAt(fila, 6).toString());
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(tblUsuarios.getSelectedRows().length > 0){
            accion = "modificar";
            modificar();
        }else{
            JOptionPane.showMessageDialog(null, "Se debe de Seleccionar un usuario");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String actualizar = null;
        if(txtVelocidad.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Velocidad obligatorio", "Validación", JOptionPane.WARNING_MESSAGE);
            txtVelocidad.requestFocusInWindow();
            return;
        }
        
        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Nombre obligatorio", "Validación", JOptionPane.WARNING_MESSAGE);
            txtNombre.requestFocusInWindow();
            return;
        }
        
        if(txtDescripción.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Descripción obligatorio", "Validación", JOptionPane.WARNING_MESSAGE);
            txtDescripción.requestFocusInWindow();
            return;
        }
        
        if(txtPrecio.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Contraseña obligatorio", "Validación", JOptionPane.WARNING_MESSAGE);
            txtPrecio.requestFocusInWindow();
            return;
        }    
        
        if(cmbTipoServicio.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(rootPane, "Campo Tipo de Servicio obligatorio", "Validación", JOptionPane.WARNING_MESSAGE);
            cmbTipoServicio.requestFocusInWindow();
            return;
        }     
        
        if(cmbEstado.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(rootPane, "Campo Estado obligatorio", "Validación", JOptionPane.WARNING_MESSAGE);
            cmbEstado.requestFocusInWindow();
            return;
        }
        
        String msg = null;
        String msg1 = null;
        String msg2 = null;
        if(txtId.getText().equals("")){
            DServicios dts = new DServicios();
            LServicios fun = new LServicios();
            DTipoServicio dtS = new DTipoServicio();
            DEstadoServicio des = new DEstadoServicio();
            
            String tipo = String.valueOf(cmbTipoServicio.getSelectedItem());
            String estado = String.valueOf(cmbEstado.getSelectedItem());
            dts.setNombreServicio(txtNombre.getText());
            dts.setVelocidadCon(txtVelocidad.getText() + " MB");
            dts.setPrecio(txtPrecio.getText());
            dts.setDescripcio(txtDescripción.getText());
            dtS.setNombre(tipo);
            des.setEstado(estado);
            msg = fun.insertarServicios(dts, dtS, des);
            mostrarBuscar("");
            if(msg == "si"){
                JOptionPane.showMessageDialog(rootPane, "Se insertó de forma correcta", "Información", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Ocurrió un problema al insertar", "Información", JOptionPane.ERROR);
            }
        }else if(accion.equals("modificar")){
            DServicios dts = new DServicios();
            LServicios fun = new LServicios();
            DTipoServicio dtS = new DTipoServicio();
            DEstadoServicio des = new DEstadoServicio();
            
            String tipo = String.valueOf(cmbTipoServicio.getSelectedItem());
            String estado = String.valueOf(cmbEstado.getSelectedItem());
            dts.setIdServicio(Integer.parseInt(txtId.getText()));
            dtS.setIdTipoServicio(Integer.parseInt(txtId.getText()));
            des.setIdestadoServicio(Integer.parseInt(txtId.getText()));
            dts.setNombreServicio(txtNombre.getText());
            dts.setVelocidadCon(txtVelocidad.getText());
            dts.setPrecio(txtPrecio.getText());
            dts.setDescripcio(txtDescripción.getText());
            dtS.setNombre(tipo);
            des.setEstado(estado);
            msg = fun.editarServicio(dts, dtS, des);
            mostrarBuscar("");
            modificar();
        }
        mostrarBotones();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(!txtId.getText().equals("")){
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "¿Desea eliminar el Usuario?", "Confirmación", 2);
            if(confirmacion == 0){
                DServicios dts = new DServicios();
                LServicios fun = new LServicios();
                DTipoServicio dtS = new DTipoServicio();
                DEstadoServicio des = new DEstadoServicio();
                
                
                dts.setIdServicio(Integer.parseInt(txtId.getText()));
                dtS.setIdTipoServicio(Integer.parseInt(txtId.getText()));
                des.setIdestadoServicio(Integer.parseInt(txtId.getText()));
                
                fun.eliminarServicios(dts, dtS, des);
                mostrarBuscar("");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        mostrarBotones();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInternetActionPerformed
        txtId.setVisible(true);
        txtNombre.setVisible(true);
        txtVelocidad.setVisible(true);
        txtVelocidad.setEnabled(true);
        txtPrecio.setVisible(true);
        txtDescripción.setVisible(true);
        cmbEstado.setVisible(true);
        cmbTipoServicio.setVisible(true);
        
        btnGuardar.setVisible(true);
        btnCancelar.setVisible(true);
        
        lblId.setVisible(true);
        lblNombre.setVisible(true);
        lblVelocidad.setVisible(true);
        lblPrecio.setVisible(true);
        lblDescripcion.setVisible(true);
        lblTipoServicio.setVisible(true);
        lblEstadoServicio.setVisible(true);
        
        btnAgregar.setVisible(false);
        btnEditar.setVisible(false);
        btnCancelarForm.setVisible(false);
        btnEliminar.setVisible(false);
        btnInternet.setVisible(false);
        btnTelefonía.setVisible(false);
    }//GEN-LAST:event_btnInternetActionPerformed

    private void btnTelefoníaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelefoníaActionPerformed
        txtId.setVisible(true);
        txtNombre.setVisible(true);
        txtVelocidad.setVisible(true);
        txtVelocidad.setEnabled(false);
        txtPrecio.setVisible(true);
        txtDescripción.setVisible(true);
        cmbEstado.setVisible(true);
        cmbTipoServicio.setVisible(true);
        
        btnGuardar.setVisible(true);
        btnCancelar.setVisible(true);
        
        lblId.setVisible(true);
        lblNombre.setVisible(true);
        lblVelocidad.setVisible(true);
        lblPrecio.setVisible(true);
        lblDescripcion.setVisible(true);
        lblTipoServicio.setVisible(true);
        lblEstadoServicio.setVisible(true);
        
        btnAgregar.setVisible(false);
        btnEditar.setVisible(false);
        btnCancelarForm.setVisible(false);
        btnEliminar.setVisible(false);
        btnInternet.setVisible(false);
        btnTelefonía.setVisible(false);
    }//GEN-LAST:event_btnTelefoníaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarForm;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInternet;
    private javax.swing.JButton btnTelefonía;
    private javax.swing.JTextField buscar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbTipoServicio;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstadoServicio;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTipoServicio;
    private javax.swing.JLabel lblVelocidad;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtDescripción;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtVelocidad;
    // End of variables declaration//GEN-END:variables
}
