/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.DEstadoServicio;
import Datos.DPersona;
import Datos.DServicios;
import Datos.DTipoServicio;
import Datos.DTipoUsuario;
import Datos.DUsuarios;
import Datos.guardarDatos;
import Logica.LEstados;
import Logica.LServicios;
import Logica.LTipoUsuario;
import Logica.LUsuarios;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josug
 */
public class frmServicios extends javax.swing.JInternalFrame {
    public static int control = 0;
    private LEstados es = new LEstados();
    public static String accion = "";
    /** Valores para editar **/
    public static int id;
    public static String nombres = "";
    public static String velocidadId = "";
    public static String velocidad = "";
    public static String precio = "";
    public static String descripcion = "";
    public static String tipoServicioId;
    public static String tipoServicio = "";
    public static String estadoId = "";
    public static String estado = "";
    /**
     * Creates new form frmUsuario
     */
    
    public frmServicios() {
        initComponents();
        mostrarBuscar("");
        
    }
    
    public void mostrarBuscar(String buscar){
        try {
            DefaultTableModel miModelo;
            LServicios log = new LServicios();
            miModelo = log.mostrarServicios(buscar);
            tblUsuarios.setModel(miModelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelarForm = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnInternet = new javax.swing.JButton();
        btnTelefonía = new javax.swing.JButton();
        btnBuscarVelocidad = new javax.swing.JToggleButton();
        btnTipoServicio = new javax.swing.JButton();
        btnAgregarVelocidad = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        buscar = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        btnGuardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 104, 88));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 104, 88));

        btnCancelarForm.setText("Cancelar");
        jPanel1.add(btnCancelarForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 104, 88));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 104, 88));

        btnInternet.setText("Internet");
        btnInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInternetActionPerformed(evt);
            }
        });
        jPanel1.add(btnInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 104, 88));

        btnTelefonía.setText("Telefonía");
        btnTelefonía.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelefoníaActionPerformed(evt);
            }
        });
        jPanel1.add(btnTelefonía, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 104, 88));

        btnBuscarVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVelocidadActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 40, 30));

        btnTipoServicio.setText("Tipo de Servicio");
        jPanel1.add(btnTipoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 104, 88));

        btnAgregarVelocidad.setText("Config. Velocidad");
        jPanel1.add(btnAgregarVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 104, 88));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        jButton5.setText("Buscar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 239, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        frmElegirServicio formulario = new frmElegirServicio();
        formulario.setVisible(true);
        formulario.toFront();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        int fila = tblUsuarios.rowAtPoint(evt.getPoint());
        id = Integer.parseInt(tblUsuarios.getValueAt(fila, 0).toString());
        nombres = (tblUsuarios.getValueAt(fila, 1).toString());
        velocidadId = tblUsuarios.getValueAt(fila, 2).toString();
        txtPrecio.setText(tblUsuarios.getValueAt(fila, 3).toString());
        txtDescripción.setText(tblUsuarios.getValueAt(fila, 4).toString());
        
        cmbEstado.setSelectedItem(tblUsuarios.getValueAt(fila, 6).toString());
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(tblUsuarios.getSelectedRows().length > 0){
            accion = "modificar";
            modificar();
        }else{
            JOptionPane.showMessageDialog(null, "Se debe de Seleccionar un usuario");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(!txtId.getText().equals("")){
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "¿Desea eliminar el Usuario?", "Confirmación", 2);
            if(confirmacion == 0){
                DServicios dts = new DServicios();
                LServicios fun = new LServicios();
                DTipoServicio dtS = new DTipoServicio();
                DEstadoServicio des = new DEstadoServicio();
                
                
                dts.setIdServicio(Integer.parseInt(txtId.getText()));
                dtS.setIdTipoServicio(Integer.parseInt(txtId.getText()));
                des.setIdestadoServicio(Integer.parseInt(txtId.getText()));
                
                fun.eliminarServicios(dts, dtS, des);
                mostrarBuscar("");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInternetActionPerformed
        txtId.setVisible(true);
        txtNombre.setVisible(true);
        txtIdVelocidad.setVisible(true);
        txtVelocidad.setVisible(true);
        txtVelocidad.setEnabled(true);
        txtPrecio.setVisible(true);
        txtDescripción.setVisible(true);
        txtIdTipo.setVisible(true);
        txtTipoServicio.setVisible(true);
        cmbEstado.setVisible(true);

        btnGuardar.setVisible(true);
        btnCancelar.setVisible(true);

        lblId.setVisible(true);
        lblNombre.setVisible(true);
        lblVelocidad.setVisible(true);
        lblPrecio.setVisible(true);
        lblDescripcion.setVisible(true);
        lblTipoServicio.setVisible(true);
        lblEstadoServicio.setVisible(true);

        btnAgregar.setVisible(false);
        btnEditar.setVisible(false);
        btnCancelarForm.setVisible(false);
        btnEliminar.setVisible(false);
        btnAgregarVelocidad.setVisible(false);
        btnTipoServicio.setVisible(false);
        btnBuscarTipoServicio.setVisible(true);
        btnBuscarVelocidad.setVisible(true);

        btnInternet.setVisible(false);
        btnTelefonía.setVisible(false);
    }//GEN-LAST:event_btnInternetActionPerformed

    private void btnTelefoníaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelefoníaActionPerformed
        txtId.setVisible(true);
        txtNombre.setVisible(true);
        txtIdVelocidad.setVisible(true);
        txtVelocidad.setVisible(true);
        txtVelocidad.setEnabled(false);
        txtPrecio.setVisible(true);
        txtDescripción.setVisible(true);
        txtIdTipo.setVisible(true);
        txtTipoServicio.setVisible(true);
        cmbEstado.setVisible(true);

        btnGuardar.setVisible(true);
        btnCancelar.setVisible(true);

        lblId.setVisible(true);
        lblNombre.setVisible(true);
        lblVelocidad.setVisible(true);
        lblPrecio.setVisible(true);
        lblDescripcion.setVisible(true);
        lblTipoServicio.setVisible(true);
        lblEstadoServicio.setVisible(true);

        btnAgregar.setVisible(false);
        btnEditar.setVisible(false);
        btnCancelarForm.setVisible(false);
        btnEliminar.setVisible(false);
        btnAgregarVelocidad.setVisible(false);
        btnTipoServicio.setVisible(false);
        btnBuscarTipoServicio.setVisible(true);
        btnBuscarVelocidad.setVisible(true);
        btnBuscarVelocidad.setEnabled(false);
        btnInternet.setVisible(false);
        btnTelefonía.setVisible(false);
    }//GEN-LAST:event_btnTelefoníaActionPerformed

    private void btnBuscarVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVelocidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarVelocidadActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String actualizar = null;
        if(txtVelocidad.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Velocidad obligatorio", "Validación", JOptionPane.WARNING_MESSAGE);
            txtVelocidad.requestFocusInWindow();
            return;
        }

        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Nombre obligatorio", "Validación", JOptionPane.WARNING_MESSAGE);
            txtNombre.requestFocusInWindow();
            return;
        }

        if(txtDescripción.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Descripción obligatorio", "Validación", JOptionPane.WARNING_MESSAGE);
            txtDescripción.requestFocusInWindow();
            return;
        }

        if(txtPrecio.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo Contraseña obligatorio", "Validación", JOptionPane.WARNING_MESSAGE);
            txtPrecio.requestFocusInWindow();
            return;
        }

        if(cmbEstado.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(rootPane, "Campo Estado obligatorio", "Validación", JOptionPane.WARNING_MESSAGE);
            cmbEstado.requestFocusInWindow();
            return;
        }

        String msg = null;
        String msg1 = null;
        String msg2 = null;
        if(txtId.getText().equals("")){
            DServicios dts = new DServicios();
            LServicios fun = new LServicios();
            DTipoServicio dtS = new DTipoServicio();
            DEstadoServicio des = new DEstadoServicio();

            String estado = String.valueOf(cmbEstado.getSelectedItem());
            dts.setNombreServicio(txtNombre.getText());
            dts.setVelocidadCon(txtVelocidad.getText() + " MB");
            dts.setPrecio(txtPrecio.getText());
            dts.setDescripcio(txtDescripción.getText());
            dtS.setNombre(txtTipoServicio.getText());
            des.setEstado(estado);
            msg = fun.insertarServicios(dts, dtS, des);
            mostrarBuscar("");
            if(msg == "si"){
                JOptionPane.showMessageDialog(rootPane, "Se insertó de forma correcta", "Información", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Ocurrió un problema al insertar", "Información", JOptionPane.ERROR);
            }
        }else if(accion.equals("modificar")){
            DServicios dts = new DServicios();
            LServicios fun = new LServicios();
            DTipoServicio dtS = new DTipoServicio();
            DEstadoServicio des = new DEstadoServicio();

            String estado = String.valueOf(cmbEstado.getSelectedItem());
            dts.setIdServicio(Integer.parseInt(txtId.getText()));
            dtS.setIdTipoServicio(Integer.parseInt(txtId.getText()));
            des.setIdestadoServicio(Integer.parseInt(txtId.getText()));
            dts.setNombreServicio(txtNombre.getText());
            dts.setVelocidadCon(txtVelocidad.getText());
            dts.setPrecio(txtPrecio.getText());
            dts.setDescripcio(txtDescripción.getText());
            dtS.setNombre(txtTipoServicio.getText());
            des.setEstado(estado);
            msg = fun.editarServicio(dts, dtS, des);
            mostrarBuscar("");
            modificar();
        }
        mostrarBotones();
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarVelocidad;
    private javax.swing.JToggleButton btnBuscarVelocidad;
    private javax.swing.JButton btnCancelarForm;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInternet;
    private javax.swing.JButton btnTelefonía;
    private javax.swing.JButton btnTipoServicio;
    private javax.swing.JTextField buscar;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
