/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Mantenimiento;

import Datos.DDetalleCuadrilla;
import Datos.DDetalleServicio;
import Datos.DPersona;
import Datos.DUsuarios;
import Logica.LConfiguracionCuadrilla;
import Logica.LServicios;
import Logica.LUsuarios;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author jotz
 */
public final class frmAgregarTrabajadores extends javax.swing.JFrame {

    public int xx;
    public int xy;

    public static String editar = "";
    public static String activar = "";
    public static String eliminar = "";
    
    public static int idDetalle;

    LConfiguracionCuadrilla lcc = new LConfiguracionCuadrilla();

    public static int idCuadrilla = 0;

    /**
     * Creates new form frmServiciosNuevo
     */
    public frmAgregarTrabajadores() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    public void mostrarBuscar(String buscar) {
        idCuadrilla = Integer.parseInt(txtIdCuadrilla.getText());
        String detalle = String.valueOf(idCuadrilla);
        try {
            DefaultTableModel miModelo;
            LConfiguracionCuadrilla log = new LConfiguracionCuadrilla();
            miModelo = log.mostrarConfiguracion(detalle);
            tblconfiguracion.setModel(miModelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void mostrarNulo(String buscar) {
        try {
            DefaultTableModel miModelo;
            LConfiguracionCuadrilla log = new LConfiguracionCuadrilla();
            miModelo = log.mostrarConfiguracionNula(buscar);
            tblconfiguracion.setModel(miModelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void ordenarTamaños() {
        TableColumnModel Modelo = tblconfiguracion.getColumnModel();
        Modelo.getColumn(0).setPreferredWidth(5);
        Modelo.getColumn(0).setResizable(false);
        Modelo.getColumn(1).setPreferredWidth(20);
        Modelo.getColumn(1).setResizable(false);
        Modelo.getColumn(2).setPreferredWidth(20);
        Modelo.getColumn(2).setResizable(false);
        Modelo.getColumn(3).setPreferredWidth(60);
        Modelo.getColumn(3).setResizable(false);
        Modelo.getColumn(4).setPreferredWidth(60);
        Modelo.getColumn(4).setResizable(false);
        Modelo.getColumn(5).setPreferredWidth(25);
        Modelo.getColumn(5).setResizable(false);
        Modelo.getColumn(6).setPreferredWidth(120);
        Modelo.getColumn(6).setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAgregarNuevoServicio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnEliminarServicio = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblEliminarServicio = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnVolver = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        btnNuevaSolicitud1 = new javax.swing.JPanel();
        btnNuevaSolicitud3 = new javax.swing.JPanel();
        btnEliminarServicioSombra = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        btnNuevaSolicitud2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        mover = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        btnMini = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnBuscarCuadrilla = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        btnReportes = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        txtCuadrilla = new javax.swing.JTextField();
        txtIdCuadrilla = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblconfiguracion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarNuevoServicio.setBackground(new java.awt.Color(102, 0, 0));
        btnAgregarNuevoServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregarNuevoServicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarNuevoServicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnAgregarNuevoServicioFocusGained(evt);
            }
        });
        btnAgregarNuevoServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarNuevoServicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarNuevoServicioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarNuevoServicioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAgregarNuevoServicioMouseReleased(evt);
            }
        });
        btnAgregarNuevoServicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_plus_math_30px_1.png"))); // NOI18N
        btnAgregarNuevoServicio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 31, 36));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("CONFIGURAR CUADRILLAS");
        btnAgregarNuevoServicio.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));
        btnAgregarNuevoServicio.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 38, 167, 10));

        jPanel2.add(btnAgregarNuevoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 240, 50));

        btnEliminarServicio.setBackground(new java.awt.Color(102, 0, 0));
        btnEliminarServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarServicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminarServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarServicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarServicioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarServicioMousePressed(evt);
            }
        });
        btnEliminarServicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_trash_30px.png"))); // NOI18N
        btnEliminarServicio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 31, 36));

        lblEliminarServicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEliminarServicio.setForeground(new java.awt.Color(204, 204, 204));
        lblEliminarServicio.setText("ELIMINAR CUADRILLAS");
        btnEliminarServicio.add(lblEliminarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 12, -1, -1));
        btnEliminarServicio.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 38, 167, 10));

        jPanel2.add(btnEliminarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 240, 50));

        btnVolver.setBackground(new java.awt.Color(102, 0, 0));
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVolverMousePressed(evt);
            }
        });
        btnVolver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_back_30px.png"))); // NOI18N
        btnVolver.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 31, 36));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("VOLVER ");
        btnVolver.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 12, -1, -1));
        btnVolver.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 38, 170, 10));

        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 240, 50));

        btnNuevaSolicitud1.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaSolicitud1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitud1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitud1FocusGained(evt);
            }
        });
        btnNuevaSolicitud1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitud1Layout = new javax.swing.GroupLayout(btnNuevaSolicitud1);
        btnNuevaSolicitud1.setLayout(btnNuevaSolicitud1Layout);
        btnNuevaSolicitud1Layout.setHorizontalGroup(
            btnNuevaSolicitud1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnNuevaSolicitud1Layout.setVerticalGroup(
            btnNuevaSolicitud1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnNuevaSolicitud1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 240, 50));

        btnNuevaSolicitud3.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaSolicitud3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitud3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitud3FocusGained(evt);
            }
        });
        btnNuevaSolicitud3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud3MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud3MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitud3Layout = new javax.swing.GroupLayout(btnNuevaSolicitud3);
        btnNuevaSolicitud3.setLayout(btnNuevaSolicitud3Layout);
        btnNuevaSolicitud3Layout.setHorizontalGroup(
            btnNuevaSolicitud3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnNuevaSolicitud3Layout.setVerticalGroup(
            btnNuevaSolicitud3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnNuevaSolicitud3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 240, 50));

        btnEliminarServicioSombra.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminarServicioSombra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarServicioSombra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminarServicioSombra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnEliminarServicioSombraFocusGained(evt);
            }
        });
        btnEliminarServicioSombra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarServicioSombraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarServicioSombraMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarServicioSombraMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEliminarServicioSombraMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnEliminarServicioSombraLayout = new javax.swing.GroupLayout(btnEliminarServicioSombra);
        btnEliminarServicioSombra.setLayout(btnEliminarServicioSombraLayout);
        btnEliminarServicioSombraLayout.setHorizontalGroup(
            btnEliminarServicioSombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnEliminarServicioSombraLayout.setVerticalGroup(
            btnEliminarServicioSombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnEliminarServicioSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 240, 50));

        jLabel21.setFont(new java.awt.Font("Bauhaus 93", 1, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("INTERNET");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 30, 50, -1));

        jLabel17.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("JOTZPOT");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel20.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("SERVINET");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, -1, -1));
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 40, 20));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 40, 20));
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 40, 10));

        jLabel23.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("TRABAJADORES");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 210, 50));

        btnActualizar.setBackground(new java.awt.Color(102, 0, 0));
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnActualizarMousePressed(evt);
            }
        });
        btnActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_back_30px.png"))); // NOI18N
        btnActualizar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 31, 36));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("ACTUALIZAR");
        btnActualizar.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 12, -1, -1));
        btnActualizar.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 38, 170, 10));

        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 240, 50));

        btnNuevaSolicitud2.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaSolicitud2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitud2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitud2FocusGained(evt);
            }
        });
        btnNuevaSolicitud2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitud2Layout = new javax.swing.GroupLayout(btnNuevaSolicitud2);
        btnNuevaSolicitud2.setLayout(btnNuevaSolicitud2Layout);
        btnNuevaSolicitud2Layout.setHorizontalGroup(
            btnNuevaSolicitud2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnNuevaSolicitud2Layout.setVerticalGroup(
            btnNuevaSolicitud2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnNuevaSolicitud2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 240, 50));

        jLabel24.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("AGREGAR ");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 130, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 590));

        mover.setBackground(new java.awt.Color(204, 204, 204));
        mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moverMouseDragged(evt);
            }
        });
        mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moverMousePressed(evt);
            }
        });
        mover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(102, 0, 0));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px.png"))); // NOI18N
        btnSalir.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 20, 20));

        mover.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, 30, 30));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        mover.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, 30, 30));

        btnMini.setBackground(new java.awt.Color(102, 0, 0));
        btnMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMiniMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMiniMouseEntered(evt);
            }
        });
        btnMini.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_minimize_window_20px.png"))); // NOI18N
        btnMini.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 20, 20));

        mover.add(btnMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, 30, 30));

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        mover.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 20, 30, 30));

        jPanel1.add(mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 60));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarCuadrilla.setBackground(new java.awt.Color(102, 0, 0));
        btnBuscarCuadrilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarCuadrillaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarCuadrillaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarCuadrillaMousePressed(evt);
            }
        });
        btnBuscarCuadrilla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_search_30px.png"))); // NOI18N
        btnBuscarCuadrilla.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel3.add(btnBuscarCuadrilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 50, 50));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 50, 50));
        jPanel3.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 180, 10));
        jPanel3.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 180, 10));
        jPanel3.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 28, 180, 10));
        jPanel3.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 18, 180, 10));

        btnReportes.setBackground(new java.awt.Color(102, 0, 0));
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnReportesMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportesMouseEntered(evt);
            }
        });
        btnReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_print_30px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        btnReportes.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 30, 38));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("Imprimir Reporte");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel25MousePressed(evt);
            }
        });
        btnReportes.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel3.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 170, 40));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setEnabled(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 170, 40));

        txtCuadrilla.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(txtCuadrilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 240, -1));

        txtIdCuadrilla.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(txtIdCuadrilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 60, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 1020, 80));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 10, 200));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 10, 200));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 10, 200));

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 10, 200));

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 10, 200));

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 10, 200));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 120, 110, 470));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 910, 60));

        jScrollPane1.setBorder(null);

        tblconfiguracion.setAutoCreateRowSorter(true);
        tblconfiguracion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblconfiguracion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblconfiguracion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblconfiguracion.setGridColor(new java.awt.Color(255, 255, 255));
        tblconfiguracion.setRowHeight(25);
        tblconfiguracion.setSelectionBackground(new java.awt.Color(102, 0, 0));
        tblconfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblconfiguracionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblconfiguracion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 880, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarNuevoServicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAgregarNuevoServicioFocusGained

    }//GEN-LAST:event_btnAgregarNuevoServicioFocusGained

    private void btnAgregarNuevoServicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarNuevoServicioMousePressed
        editar = "no";
        frmValoresConfiguracion form = new frmValoresConfiguracion();
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_btnAgregarNuevoServicioMousePressed

    private void btnAgregarNuevoServicioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarNuevoServicioMouseReleased

    }//GEN-LAST:event_btnAgregarNuevoServicioMouseReleased

    private void btnAgregarNuevoServicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarNuevoServicioMouseExited
        resetColor(btnAgregarNuevoServicio);
    }//GEN-LAST:event_btnAgregarNuevoServicioMouseExited

    private void btnAgregarNuevoServicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarNuevoServicioMouseEntered
        setColor(btnAgregarNuevoServicio);
    }//GEN-LAST:event_btnAgregarNuevoServicioMouseEntered

    private void btnEliminarServicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarServicioMousePressed
        eliminar = "si";
        if (!"".equals(idDetalle)) {
            int mensaje = JOptionPane.showConfirmDialog(rootPane, "¿Desea quitar el trabajador de la cuadrilla?");
            if (mensaje == 0) {
                DDetalleCuadrilla ddc = new DDetalleCuadrilla();
                LConfiguracionCuadrilla fun = new LConfiguracionCuadrilla();

                ddc.setIdDetalleCuadrilla(idDetalle);
                fun.eliminarTrabajador(ddc);
            }
        }

    }//GEN-LAST:event_btnEliminarServicioMousePressed

    private void btnEliminarServicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarServicioMouseExited
        resetColor(btnEliminarServicio);
    }//GEN-LAST:event_btnEliminarServicioMouseExited

    private void btnEliminarServicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarServicioMouseEntered
        setColor(btnEliminarServicio);
    }//GEN-LAST:event_btnEliminarServicioMouseEntered

    private void btnVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMousePressed
        frmCuadrillaNuevo form = new frmCuadrillaNuevo();
        form.setVisible(true);
        form.toFront();
        this.dispose();
    }//GEN-LAST:event_btnVolverMousePressed

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        resetColor(btnVolver);
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        setColor(btnVolver);
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnNuevaSolicitud1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1FocusGained

    private void btnNuevaSolicitud1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1MousePressed

    private void btnNuevaSolicitud1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1MouseReleased

    private void btnNuevaSolicitud1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1MouseExited

    private void btnNuevaSolicitud1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1MouseEntered

    private void btnNuevaSolicitud3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud3FocusGained

    private void btnNuevaSolicitud3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud3MousePressed

    private void btnNuevaSolicitud3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud3MouseReleased

    private void btnNuevaSolicitud3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud3MouseExited

    private void btnNuevaSolicitud3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud3MouseEntered

    private void btnEliminarServicioSombraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnEliminarServicioSombraFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarServicioSombraFocusGained

    private void btnEliminarServicioSombraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarServicioSombraMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarServicioSombraMousePressed

    private void btnEliminarServicioSombraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarServicioSombraMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarServicioSombraMouseReleased

    private void btnEliminarServicioSombraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarServicioSombraMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarServicioSombraMouseExited

    private void btnEliminarServicioSombraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarServicioSombraMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarServicioSombraMouseEntered

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        this.dispose();
    }//GEN-LAST:event_btnSalirMousePressed

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        resetColor(btnSalir);
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        setColor(btnSalir);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnMiniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiniMouseExited
        resetColor(btnMini);
    }//GEN-LAST:event_btnMiniMouseExited

    private void btnMiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiniMouseEntered
        setColor(btnMini);
    }//GEN-LAST:event_btnMiniMouseEntered

    private void moverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_moverMouseDragged

    private void moverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_moverMousePressed

    private void btnBuscarCuadrillaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCuadrillaMouseExited
        resetColor(btnBuscarCuadrilla);
    }//GEN-LAST:event_btnBuscarCuadrillaMouseExited

    private void btnBuscarCuadrillaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCuadrillaMouseEntered
        setColor(btnBuscarCuadrilla);
    }//GEN-LAST:event_btnBuscarCuadrillaMouseEntered

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed

    }//GEN-LAST:event_jLabel11MousePressed

    private void jLabel25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MousePressed

    private void btnReportesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMousePressed

    }//GEN-LAST:event_btnReportesMousePressed

    private void btnReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseExited
        resetColor(btnReportes);
    }//GEN-LAST:event_btnReportesMouseExited

    private void btnReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseEntered
        setColor(btnReportes);
    }//GEN-LAST:event_btnReportesMouseEntered

    private void tblconfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblconfiguracionMouseClicked
        int fila = tblconfiguracion.rowAtPoint(evt.getPoint());
        idDetalle = Integer.parseInt(tblconfiguracion.getValueAt(fila, 0).toString());
        
        System.out.println(idDetalle);
    }//GEN-LAST:event_tblconfiguracionMouseClicked

    private void btnNuevaSolicitud2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud2FocusGained

    private void btnNuevaSolicitud2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud2MousePressed

    private void btnNuevaSolicitud2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud2MouseReleased

    private void btnNuevaSolicitud2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud2MouseExited

    private void btnNuevaSolicitud2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud2MouseEntered

    private void btnActualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMousePressed
        mostrarBuscar("");
        ordenarTamaños();
    }//GEN-LAST:event_btnActualizarMousePressed

    private void btnActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarMouseExited

    private void btnActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarMouseEntered

    private void btnBuscarCuadrillaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCuadrillaMousePressed
        tblconfiguracion.setModel(new DefaultTableModel());
        frmVistaCuadrillaBuscar form = new frmVistaCuadrillaBuscar();
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_btnBuscarCuadrillaMousePressed

    public void eliminar() {
        DefaultTableModel tb = (DefaultTableModel) tblconfiguracion.getModel();
        int a = tblconfiguracion.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }
    }

    void setColor(JPanel panel) {
        panel.setBackground(new Color(51, 0, 0));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(102, 0, 0));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAgregarTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAgregarTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAgregarTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAgregarTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAgregarTrabajadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnActualizar;
    private javax.swing.JPanel btnAgregarNuevoServicio;
    private javax.swing.JPanel btnBuscarCuadrilla;
    private javax.swing.JPanel btnEliminarServicio;
    private javax.swing.JPanel btnEliminarServicioSombra;
    private javax.swing.JPanel btnMini;
    private javax.swing.JPanel btnNuevaSolicitud1;
    private javax.swing.JPanel btnNuevaSolicitud2;
    private javax.swing.JPanel btnNuevaSolicitud3;
    private javax.swing.JPanel btnReportes;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JPanel btnVolver;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblEliminarServicio;
    private javax.swing.JPanel mover;
    private javax.swing.JTable tblconfiguracion;
    public static javax.swing.JTextField txtCuadrilla;
    public static javax.swing.JTextField txtIdCuadrilla;
    // End of variables declaration//GEN-END:variables
}
