/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Clientes;

import Datos.DCaja;
import Datos.DDetalleMonto;
import Datos.DUsuarios;
import Presentacion.Mantenimiento.*;
import Logica.ConexionSingleton;
import Logica.LCaja;
import Presentacion.Clientes.frmPrincipalMenu;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author josug
 */
public class frmCerrarCaja extends javax.swing.JFrame {
    LCaja lc = new LCaja();
    Connection cn = ConexionSingleton.getConnection();
    public static int idCaja;
    public static int idMonto;
    public static double montoTotal;
    public static double montoApertura;
    
    public frmCerrarCaja() {
        initComponents();
        this.setLocationRelativeTo(null);
        idCaja = lc.traerId();
        idMonto = lc.traerIdMonto();
        montoTotal = lc.traerMontoFinal();
        montoApertura = lc.traerMonto();
        traerDatos();
    }
    
    void traerDatos(){
        txtIdCaja.setText(String.valueOf(idCaja));
        txtMontoApertura.setText(String.valueOf(montoApertura));
        txtMontoCierre.setText(String.valueOf(montoTotal));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAbrirCaja = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnNuevaSolicitud5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnEditarSolicitud2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnNuevaSolicitud6 = new javax.swing.JPanel();
        txtMontoCierre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMontoApertura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIdCaja = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 40));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAbrirCaja.setBackground(new java.awt.Color(102, 0, 0));
        btnAbrirCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbrirCaja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAbrirCaja.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnAbrirCajaFocusGained(evt);
            }
        });
        btnAbrirCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAbrirCajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAbrirCajaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAbrirCajaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAbrirCajaMouseReleased(evt);
            }
        });
        btnAbrirCaja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Cerrar Caja");
        btnAbrirCaja.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));
        btnAbrirCaja.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 10));

        jPanel1.add(btnAbrirCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, 40));

        btnNuevaSolicitud5.setBackground(new java.awt.Color(51, 0, 0));
        btnNuevaSolicitud5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevaSolicitud5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitud5FocusGained(evt);
            }
        });
        btnNuevaSolicitud5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud5MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitud5Layout = new javax.swing.GroupLayout(btnNuevaSolicitud5);
        btnNuevaSolicitud5.setLayout(btnNuevaSolicitud5Layout);
        btnNuevaSolicitud5Layout.setHorizontalGroup(
            btnNuevaSolicitud5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        btnNuevaSolicitud5Layout.setVerticalGroup(
            btnNuevaSolicitud5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnNuevaSolicitud5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 100, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gs.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 320, 30));

        btnEditarSolicitud2.setBackground(new java.awt.Color(102, 0, 0));
        btnEditarSolicitud2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarSolicitud2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditarSolicitud2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnEditarSolicitud2FocusGained(evt);
            }
        });
        btnEditarSolicitud2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarSolicitud2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarSolicitud2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarSolicitud2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditarSolicitud2MouseReleased(evt);
            }
        });
        btnEditarSolicitud2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Cancelar");
        btnEditarSolicitud2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));
        btnEditarSolicitud2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 20));

        jPanel1.add(btnEditarSolicitud2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 90, 40));

        btnNuevaSolicitud6.setBackground(new java.awt.Color(51, 0, 0));
        btnNuevaSolicitud6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevaSolicitud6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitud6FocusGained(evt);
            }
        });
        btnNuevaSolicitud6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud6MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitud6Layout = new javax.swing.GroupLayout(btnNuevaSolicitud6);
        btnNuevaSolicitud6.setLayout(btnNuevaSolicitud6Layout);
        btnNuevaSolicitud6Layout.setHorizontalGroup(
            btnNuevaSolicitud6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        btnNuevaSolicitud6Layout.setVerticalGroup(
            btnNuevaSolicitud6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnNuevaSolicitud6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));
        jPanel1.add(txtMontoCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Monto de Cierre:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Monto Apertura:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        jPanel1.add(txtMontoApertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 100, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gs.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));
        jPanel1.add(txtIdCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 50, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Id Caja:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 370, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaSolicitud5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud5FocusGained

    private void btnNuevaSolicitud5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud5MouseEntered

    private void btnNuevaSolicitud5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud5MouseExited

    private void btnNuevaSolicitud5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud5MousePressed

    private void btnNuevaSolicitud5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud5MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud5MouseReleased

    private void btnAbrirCajaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAbrirCajaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbrirCajaFocusGained

    private void btnAbrirCajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirCajaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbrirCajaMouseEntered

    private void btnAbrirCajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirCajaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbrirCajaMouseExited

    private void btnAbrirCajaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirCajaMousePressed
        DDetalleMonto ddm = new DDetalleMonto();
        DCaja dc = new DCaja();
        LCaja fun = new LCaja();
        
        ddm.setIdDetalleMonto(idCaja);
        ddm.setCantidadTotal(montoTotal);
        ddm.setMontoId(idMonto);
        ddm.setCajaId(idCaja);
        dc.setIdCaja(idCaja);
        
        fun.RealizarCarga(dc, ddm);
    }//GEN-LAST:event_btnAbrirCajaMousePressed

    private void btnAbrirCajaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirCajaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbrirCajaMouseReleased

    private void btnNuevaSolicitud6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud6FocusGained

    private void btnNuevaSolicitud6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud6MouseEntered

    private void btnNuevaSolicitud6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud6MouseExited

    private void btnNuevaSolicitud6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud6MousePressed

    private void btnNuevaSolicitud6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud6MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud6MouseReleased

    private void btnEditarSolicitud2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnEditarSolicitud2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarSolicitud2FocusGained

    private void btnEditarSolicitud2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarSolicitud2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarSolicitud2MouseEntered

    private void btnEditarSolicitud2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarSolicitud2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarSolicitud2MouseExited

    private void btnEditarSolicitud2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarSolicitud2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarSolicitud2MousePressed

    private void btnEditarSolicitud2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarSolicitud2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarSolicitud2MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCerrarCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCerrarCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCerrarCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCerrarCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCerrarCaja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAbrirCaja;
    private javax.swing.JPanel btnEditarSolicitud2;
    private javax.swing.JPanel btnNuevaSolicitud5;
    private javax.swing.JPanel btnNuevaSolicitud6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtIdCaja;
    private javax.swing.JTextField txtMontoApertura;
    private javax.swing.JTextField txtMontoCierre;
    // End of variables declaration//GEN-END:variables
}
