/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Clientes;

import Datos.DCaja;
import Datos.DDetalleFactura;
import Datos.DDetallePagos;
import Datos.DPagos;
import Datos.DServiciodelCliente;
import Logica.ConexionSingleton;
import Logica.LCaja;
import Logica.LGestionarServicios;
import Logica.LPagos;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author josug
 */
public class frmGestionarPagos extends javax.swing.JFrame {

    public int xx;
    public int xy;
    public static int idFactura;
    public static int idCliente;
    public static String nombreCliente;
    public static String nroCedula;
    public static String fechaVencimiento;
    public static Date fechaPago;
    public static String servicioCliente;
    public static double total;
    LCaja lc = new LCaja();
    LGestionarServicios lgs = new LGestionarServicios();
    public static double montoD;
    public static String estado;
    public static double multa;
    public static double vuelto;

    /**
     * Creates new form frmPrincipalSolicitudesNuevo
     */
    public frmGestionarPagos() {
        initComponents();
        mostrarBuscar("");
        ordenarTamaños();
        this.setLocationRelativeTo(null);
        montoD = lc.traerMonto();
        estado = lc.traerEstado();
        estadoCaja();
        mensaje();
        lblrevertir.setVisible(false);
    }

    void estadoCaja() {
        if (!"Abierta".equals(estado)) {
            lblEstadodeCaja.setText("Caja Cerrada");

        } else if ("Abierta".equals(estado)) {
            lblEstadodeCaja.setText("Caja " + estado);
            lblEstado.setText("Cerrar Caja");
        }
    }

    void mensaje() {
        Timer timer = new Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                if (montoD == 0) {
                    frmMontoNuevo form = new frmMontoNuevo();
                    form.setVisible(true);
                }
            }
        });
        timer.setRepeats(false);
        timer.start();
    }

    public void mostrarBuscar(String buscar) {
        try {
            DefaultTableModel miModelo;
            LPagos log = new LPagos();
            miModelo = log.mostrarPagos(buscar);
            tblPagos.setModel(miModelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void mostrarFacturasSinPagar(String buscar) {
        try {
            DefaultTableModel miModelo;
            LPagos log = new LPagos();
            miModelo = log.mostrarFacturaNoPagada(buscar);
            tblPagos.setModel(miModelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void ordenarTamaños() {
        TableColumnModel Modelo = tblPagos.getColumnModel();
        Modelo.getColumn(0).setPreferredWidth(10);
        Modelo.getColumn(0).setResizable(false);
        Modelo.getColumn(1).setPreferredWidth(10);
        Modelo.getColumn(1).setResizable(false);
        Modelo.getColumn(2).setPreferredWidth(90);
        Modelo.getColumn(2).setResizable(false);
        Modelo.getColumn(3).setPreferredWidth(35);
        Modelo.getColumn(3).setResizable(false);
        Modelo.getColumn(4).setPreferredWidth(40);
        Modelo.getColumn(4).setResizable(false);
        Modelo.getColumn(5).setPreferredWidth(45);
        Modelo.getColumn(5).setResizable(false);
        Modelo.getColumn(6).setPreferredWidth(80);
        Modelo.getColumn(6).setResizable(false);
        Modelo.getColumn(7).setPreferredWidth(30);
        Modelo.getColumn(7).setResizable(false);
        Modelo.getColumn(8).setPreferredWidth(55);
        Modelo.getColumn(8).setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the
     * form.+ WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnRealizarPago = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnVolver = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        btnNuevaSolicitud1 = new javax.swing.JPanel();
        btnNuevaSolicitud3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        btnNuevaSolicitud5 = new javax.swing.JPanel();
        btnRevisarPagos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnNuevaSolicitud6 = new javax.swing.JPanel();
        btnCancelarPago = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnNuevaSolicitud4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblEstadodeCaja = new javax.swing.JLabel();
        btnCerrarCaja = new javax.swing.JPanel();
        lblEstado = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        btnReportes = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPagos = new javax.swing.JTable();
        mover = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        btnMini = new javax.swing.JPanel();
        lblMini = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        btnMostrarServiciosActivos = new javax.swing.JPanel();
        lblrevertir = new javax.swing.JLabel();
        lblAceptado = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRealizarPago.setBackground(new java.awt.Color(102, 0, 0));
        btnRealizarPago.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRealizarPago.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRealizarPago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnRealizarPagoFocusGained(evt);
            }
        });
        btnRealizarPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRealizarPagoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRealizarPagoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRealizarPagoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRealizarPagoMouseReleased(evt);
            }
        });
        btnRealizarPago.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_plus_math_30px_1.png"))); // NOI18N
        btnRealizarPago.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 31, 36));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Realizar Pago");
        btnRealizarPago.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 12, -1, -1));
        btnRealizarPago.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 38, 167, 10));

        jPanel2.add(btnRealizarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 240, 50));

        btnVolver.setBackground(new java.awt.Color(102, 0, 0));
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVolverMousePressed(evt);
            }
        });
        btnVolver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_back_30px.png"))); // NOI18N
        btnVolver.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 31, 36));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Volver");
        btnVolver.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 12, -1, -1));
        btnVolver.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 38, 167, 10));

        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 240, 50));

        btnNuevaSolicitud1.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaSolicitud1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitud1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitud1FocusGained(evt);
            }
        });
        btnNuevaSolicitud1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitud1Layout = new javax.swing.GroupLayout(btnNuevaSolicitud1);
        btnNuevaSolicitud1.setLayout(btnNuevaSolicitud1Layout);
        btnNuevaSolicitud1Layout.setHorizontalGroup(
            btnNuevaSolicitud1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnNuevaSolicitud1Layout.setVerticalGroup(
            btnNuevaSolicitud1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnNuevaSolicitud1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 240, 50));

        btnNuevaSolicitud3.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaSolicitud3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitud3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitud3FocusGained(evt);
            }
        });
        btnNuevaSolicitud3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud3MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud3MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitud3Layout = new javax.swing.GroupLayout(btnNuevaSolicitud3);
        btnNuevaSolicitud3.setLayout(btnNuevaSolicitud3Layout);
        btnNuevaSolicitud3Layout.setHorizontalGroup(
            btnNuevaSolicitud3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnNuevaSolicitud3Layout.setVerticalGroup(
            btnNuevaSolicitud3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnNuevaSolicitud3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 240, 50));

        jLabel21.setFont(new java.awt.Font("Bauhaus 93", 1, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("INTERNET");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 30, 50, -1));

        jLabel17.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("JOTZPOT");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel20.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("SERVINET");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, -1, -1));
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 40, 20));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 40, 20));
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 40, 10));

        jLabel23.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("PAGO DE SERVICIOS");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 260, 50));

        btnActualizar.setBackground(new java.awt.Color(102, 0, 0));
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnActualizarMousePressed(evt);
            }
        });
        btnActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_back_30px.png"))); // NOI18N
        btnActualizar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 31, 36));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Actualizar");
        btnActualizar.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 12, -1, -1));
        btnActualizar.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 38, 167, 10));

        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 240, 50));

        btnNuevaSolicitud5.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaSolicitud5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitud5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitud5FocusGained(evt);
            }
        });
        btnNuevaSolicitud5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud5MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitud5Layout = new javax.swing.GroupLayout(btnNuevaSolicitud5);
        btnNuevaSolicitud5.setLayout(btnNuevaSolicitud5Layout);
        btnNuevaSolicitud5Layout.setHorizontalGroup(
            btnNuevaSolicitud5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnNuevaSolicitud5Layout.setVerticalGroup(
            btnNuevaSolicitud5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnNuevaSolicitud5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 240, 50));

        btnRevisarPagos.setBackground(new java.awt.Color(102, 0, 0));
        btnRevisarPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRevisarPagos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRevisarPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRevisarPagosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRevisarPagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRevisarPagosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRevisarPagosMousePressed(evt);
            }
        });
        btnRevisarPagos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_trash_30px.png"))); // NOI18N
        btnRevisarPagos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 31, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Revisar Pagos");
        btnRevisarPagos.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 12, -1, -1));
        btnRevisarPagos.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 38, 167, 10));

        jPanel2.add(btnRevisarPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 240, 50));

        btnNuevaSolicitud6.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaSolicitud6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitud6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitud6FocusGained(evt);
            }
        });
        btnNuevaSolicitud6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud6MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitud6Layout = new javax.swing.GroupLayout(btnNuevaSolicitud6);
        btnNuevaSolicitud6.setLayout(btnNuevaSolicitud6Layout);
        btnNuevaSolicitud6Layout.setHorizontalGroup(
            btnNuevaSolicitud6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnNuevaSolicitud6Layout.setVerticalGroup(
            btnNuevaSolicitud6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnNuevaSolicitud6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 240, 50));

        btnCancelarPago.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelarPago.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelarPago.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelarPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarPagoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarPagoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarPagoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelarPagoMousePressed(evt);
            }
        });
        btnCancelarPago.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_trash_30px.png"))); // NOI18N
        btnCancelarPago.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 31, 36));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Cancelar Pago");
        btnCancelarPago.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));
        btnCancelarPago.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 38, 170, 10));

        jPanel2.add(btnCancelarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 240, 50));

        btnNuevaSolicitud4.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaSolicitud4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitud4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitud4FocusGained(evt);
            }
        });
        btnNuevaSolicitud4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud4MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitud4Layout = new javax.swing.GroupLayout(btnNuevaSolicitud4);
        btnNuevaSolicitud4.setLayout(btnNuevaSolicitud4Layout);
        btnNuevaSolicitud4Layout.setHorizontalGroup(
            btnNuevaSolicitud4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnNuevaSolicitud4Layout.setVerticalGroup(
            btnNuevaSolicitud4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnNuevaSolicitud4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 240, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 590));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setBackground(new java.awt.Color(204, 204, 204));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        jPanel3.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 32, 160, -1));

        btnBuscar.setBackground(new java.awt.Color(102, 0, 0));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });
        btnBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_search_30px_1.png"))); // NOI18N
        btnBuscar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel3.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 50, 50));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 50, 50));

        lblEstadodeCaja.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        lblEstadodeCaja.setForeground(new java.awt.Color(204, 204, 204));
        lblEstadodeCaja.setText("ESTADO DE CAJA");
        jPanel3.add(lblEstadodeCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 200, 50));

        btnCerrarCaja.setBackground(new java.awt.Color(102, 0, 0));
        btnCerrarCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarCajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarCajaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarCajaMousePressed(evt);
            }
        });
        btnCerrarCaja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(204, 204, 204));
        lblEstado.setText("ESTADO");
        btnCerrarCaja.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel3.add(btnCerrarCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 120, 30));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 120, -1));

        btnReportes.setBackground(new java.awt.Color(102, 0, 0));
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnReportesMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportesMouseEntered(evt);
            }
        });
        btnReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_print_30px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        btnReportes.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 30, 38));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("Imprimir Reporte");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel25MousePressed(evt);
            }
        });
        btnReportes.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel3.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 170, 40));

        jPanel15.setBackground(new java.awt.Color(0, 0, 0));
        jPanel15.setEnabled(false);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 170, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 930, 80));

        jScrollPane1.setBorder(null);

        tblPagos.setAutoCreateRowSorter(true);
        tblPagos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblPagos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblPagos.setGridColor(new java.awt.Color(255, 255, 255));
        tblPagos.setRowHeight(25);
        tblPagos.setSelectionBackground(new java.awt.Color(102, 0, 0));
        tblPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPagosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPagos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 790, 370));

        mover.setBackground(new java.awt.Color(204, 204, 204));
        mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moverMouseDragged(evt);
            }
        });
        mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moverMousePressed(evt);
            }
        });
        mover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(102, 0, 0));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px.png"))); // NOI18N
        btnSalir.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 20, 20));

        mover.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 30, 30));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        mover.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 20, 30, 30));

        btnMini.setBackground(new java.awt.Color(102, 0, 0));
        btnMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMiniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMiniMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMiniMousePressed(evt);
            }
        });
        btnMini.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_minimize_window_20px.png"))); // NOI18N
        lblMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMiniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMiniMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMiniMousePressed(evt);
            }
        });
        btnMini.add(lblMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 20, 20));

        mover.add(btnMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 30, 30));

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        mover.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, 30, 30));

        jPanel1.add(mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 60));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 10, 200));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 10, 200));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 10, 200));

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 10, 200));

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 10, 200));

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 10, 200));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 120, 110, 470));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrarServiciosActivos.setBackground(new java.awt.Color(102, 0, 0));
        btnMostrarServiciosActivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMostrarServiciosActivosMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarServiciosActivosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarServiciosActivosMouseEntered(evt);
            }
        });
        btnMostrarServiciosActivos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblrevertir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblrevertir.setForeground(new java.awt.Color(204, 204, 204));
        lblrevertir.setText("REVERTIR");
        btnMostrarServiciosActivos.add(lblrevertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        lblAceptado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAceptado.setForeground(new java.awt.Color(204, 204, 204));
        lblAceptado.setText("FACTURAS SIN PAGAR");
        btnMostrarServiciosActivos.add(lblAceptado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel10.add(btnMostrarServiciosActivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 160, 30));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 160, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MOSTRAR:");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 820, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarPagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarPagoMousePressed
        frmGenerarPago form = new frmGenerarPago();
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_btnRealizarPagoMousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed

    }//GEN-LAST:event_jPanel1MousePressed

    private void moverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_moverMouseDragged

    private void moverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_moverMousePressed

    private void btnRealizarPagoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarPagoMouseReleased

    }//GEN-LAST:event_btnRealizarPagoMouseReleased

    private void btnRealizarPagoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnRealizarPagoFocusGained

    }//GEN-LAST:event_btnRealizarPagoFocusGained

    private void btnRealizarPagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarPagoMouseEntered
        setColor(btnRealizarPago);
    }//GEN-LAST:event_btnRealizarPagoMouseEntered

    private void btnRealizarPagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarPagoMouseExited
        resetColor(btnRealizarPago);
    }//GEN-LAST:event_btnRealizarPagoMouseExited

    private void btnVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMousePressed
        frmPrincipalMenu form = new frmPrincipalMenu();
        form.setVisible(true);
        form.toFront();
        this.dispose();
    }//GEN-LAST:event_btnVolverMousePressed

    private void tblPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPagosMouseClicked
        int fila = tblPagos.rowAtPoint(evt.getPoint());
        idFactura = Integer.parseInt(tblPagos.getValueAt(fila, 0).toString());
        idCliente = Integer.parseInt(tblPagos.getValueAt(fila, 1).toString());
        nombreCliente = tblPagos.getValueAt(fila, 2).toString();
        nroCedula = tblPagos.getValueAt(fila, 3).toString();
        fechaVencimiento = tblPagos.getValueAt(fila, 5).toString();
        fechaPago = lgs.traerFecha(idCliente);
        System.out.println(fechaPago);
        servicioCliente = tblPagos.getValueAt(fila, 6).toString();
        total = Double.parseDouble(tblPagos.getValueAt(fila, 7).toString());
        multa = lgs.traerSobrecargo(idCliente);
        if (multa > 0) {
            System.out.println(multa);
        }
    }//GEN-LAST:event_tblPagosMouseClicked

    private void btnNuevaSolicitud1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1FocusGained

    private void btnNuevaSolicitud1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1MouseEntered

    private void btnNuevaSolicitud1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1MouseExited

    private void btnNuevaSolicitud1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1MousePressed

    private void btnNuevaSolicitud1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1MouseReleased

    private void btnNuevaSolicitud3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud3FocusGained

    private void btnNuevaSolicitud3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud3MouseEntered

    private void btnNuevaSolicitud3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud3MouseExited

    private void btnNuevaSolicitud3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud3MousePressed

    private void btnNuevaSolicitud3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud3MouseReleased

    private void btnMostrarServiciosActivosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarServiciosActivosMousePressed

        if (lblAceptado.isVisible()) {
            lblAceptado.setVisible(false);
            lblrevertir.setVisible(true);
            mostrarFacturasSinPagar("");
            ordenarTamaños();
        } else {
            lblAceptado.setVisible(true);
            lblrevertir.setVisible(false);
            mostrarBuscar("");
            ordenarTamaños();
        }
    }//GEN-LAST:event_btnMostrarServiciosActivosMousePressed

    private void btnCerrarCajaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarCajaMousePressed
        int mensaje = JOptionPane.showConfirmDialog(rootPane, "¿Desea cerrar la caja?", "Confirmación", 2);
        if (mensaje == 0) {
            frmCerrarCaja form = new frmCerrarCaja();
            form.setVisible(true);
            form.toFront();
        }
    }//GEN-LAST:event_btnCerrarCajaMousePressed

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        if ("Abierto".equals(estado)) {
            JOptionPane.showMessageDialog(null, "La caja está abierta");
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirMousePressed

    private void btnActualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMousePressed
        Connection cn = ConexionSingleton.getConnection();
        if (!lblAceptado.isVisible()) {
            mostrarFacturasSinPagar("");
            ordenarTamaños();
        } else {
            mostrarBuscar("");
            ordenarTamaños();
        }
    }//GEN-LAST:event_btnActualizarMousePressed

    private void btnNuevaSolicitud5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud5FocusGained

    private void btnNuevaSolicitud5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud5MousePressed

    private void btnNuevaSolicitud5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud5MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud5MouseReleased

    private void btnNuevaSolicitud5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud5MouseExited

    private void btnNuevaSolicitud5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud5MouseEntered

    private void btnActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseEntered
        setColor(btnActualizar);
    }//GEN-LAST:event_btnActualizarMouseEntered

    private void btnActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseExited
        resetColor(btnActualizar);
    }//GEN-LAST:event_btnActualizarMouseExited

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        setColor(btnVolver);
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        resetColor(btnVolver);
    }//GEN-LAST:event_btnVolverMouseExited

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        frmElegirReporteServicios form = new frmElegirReporteServicios();
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_jLabel11MousePressed

    private void jLabel25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MousePressed

    private void btnReportesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMousePressed
        frmElegirReportePagos form = new frmElegirReportePagos();
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_btnReportesMousePressed

    private void btnReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseExited
        resetColor(btnReportes);
    }//GEN-LAST:event_btnReportesMouseExited

    private void btnReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseEntered
        setColor(btnReportes);
    }//GEN-LAST:event_btnReportesMouseEntered

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered

    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited

    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnCerrarCajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarCajaMouseEntered
        setColor(btnCerrarCaja);
    }//GEN-LAST:event_btnCerrarCajaMouseEntered

    private void btnCerrarCajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarCajaMouseExited
        resetColor(btnCerrarCaja);
    }//GEN-LAST:event_btnCerrarCajaMouseExited

    private void btnMostrarServiciosActivosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarServiciosActivosMouseEntered
        setColor(btnMostrarServiciosActivos);
    }//GEN-LAST:event_btnMostrarServiciosActivosMouseEntered

    private void btnMostrarServiciosActivosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarServiciosActivosMouseExited
        resetColor(btnMostrarServiciosActivos);
    }//GEN-LAST:event_btnMostrarServiciosActivosMouseExited

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        setColor(btnSalir);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        resetColor(btnSalir);
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnMiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiniMouseEntered
        setColor(btnMini);
    }//GEN-LAST:event_btnMiniMouseEntered

    private void btnMiniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiniMouseExited
        resetColor(btnMini);
    }//GEN-LAST:event_btnMiniMouseExited

    private void btnNuevaSolicitud6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud6FocusGained

    private void btnNuevaSolicitud6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud6MousePressed

    private void btnNuevaSolicitud6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud6MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud6MouseReleased

    private void btnNuevaSolicitud6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud6MouseExited

    private void btnNuevaSolicitud6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud6MouseEntered

    private void btnRevisarPagosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarPagosMousePressed
        frmRevisarPagos form = new frmRevisarPagos();
        form.setVisible(true);
        form.toFront();
        this.dispose();
    }//GEN-LAST:event_btnRevisarPagosMousePressed

    private void btnRevisarPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarPagosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRevisarPagosMouseClicked

    private void btnRevisarPagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarPagosMouseExited
        resetColor(btnRevisarPagos);
    }//GEN-LAST:event_btnRevisarPagosMouseExited

    private void btnRevisarPagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarPagosMouseEntered
        setColor(btnRevisarPagos);
    }//GEN-LAST:event_btnRevisarPagosMouseEntered

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        if (!lblAceptado.isVisible()) {
            mostrarFacturasSinPagar(txtBuscar.getText());
            ordenarTamaños();
        } else {
            mostrarBuscar(txtBuscar.getText());
            ordenarTamaños();
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresa solo el Nro de Cedula");
            txtBuscar.setText("");
            txtBuscar.requestFocus();
        }
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void lblMiniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMiniMousePressed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMiniMousePressed

    private void btnMiniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiniMousePressed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMiniMousePressed

    private void lblMiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMiniMouseEntered
        setColor(btnMini);
    }//GEN-LAST:event_lblMiniMouseEntered

    private void lblMiniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMiniMouseExited
        resetColor(btnMini);
    }//GEN-LAST:event_lblMiniMouseExited

    private void btnCancelarPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarPagoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarPagoMouseClicked

    private void btnCancelarPagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarPagoMouseEntered
        setColor(btnCancelarPago);
    }//GEN-LAST:event_btnCancelarPagoMouseEntered

    private void btnCancelarPagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarPagoMouseExited
        resetColor(btnCancelarPago);
    }//GEN-LAST:event_btnCancelarPagoMouseExited

    private void btnCancelarPagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarPagoMousePressed
        int mensaje = JOptionPane.showConfirmDialog(rootPane, "¿Desea cancelar el Pago?", "Confirmación", 2);
        if (mensaje == 0) {
            DPagos dp = new DPagos();
            DDetalleFactura ddf = new DDetalleFactura();
            DDetallePagos ddp = new DDetallePagos();
            DCaja dc = new DCaja();
            DServiciodelCliente dsc = new DServiciodelCliente();
            LPagos fun = new LPagos();
            LGestionarServicios fun1 = new LGestionarServicios();
            
            SimpleDateFormat diaF = new SimpleDateFormat("dd");
            SimpleDateFormat mesF = new SimpleDateFormat("MM");
            SimpleDateFormat añoF = new SimpleDateFormat("yyyy");
            
            int año = Integer.parseInt(añoF.format(fechaPago.getTime()));
            int mes = Integer.parseInt(mesF.format(fechaPago.getTime()));
            int dia = Integer.parseInt(diaF.format(fechaPago.getTime()));
            
            int mesA = mes - 1;
            
            dsc.setFechaPago(new Date((año - 1900), mesA, dia));
            dsc.setMulta(multa);
            dsc.setEstadoMulta("SI");
            fun1.multa(dsc);
            
            dsc.setIdServiciodelCliente(idCliente);

            fun1.EstadoCancelado(dsc);

            int idCaja = lc.traerId();
            int monto = lc.traerIdMonto();
            double montoAnterior = lc.traerMonto();
            
            double montoSuma = montoAnterior + vuelto;
            System.out.println(vuelto);
            dc.setMontoApertura(montoSuma);
            dc.setIdCaja(idCaja);
            fun.restarMonto(dc);

            int idPagos = fun.traerIdPagos(idCliente);
            dp.setIdPagos(idPagos);
            
            ddf.setIdDetalleFactura(idFactura);
            System.out.println(idFactura);
            fun.CancelarPago(dp, ddf, dsc);
            JOptionPane.showMessageDialog(null, "Pago Cancelado");
        }
    }//GEN-LAST:event_btnCancelarPagoMousePressed

    private void btnNuevaSolicitud4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud4FocusGained

    private void btnNuevaSolicitud4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud4MouseEntered

    private void btnNuevaSolicitud4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud4MouseExited

    private void btnNuevaSolicitud4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud4MousePressed

    private void btnNuevaSolicitud4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud4MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud4MouseReleased

    void setColor(JPanel panel) {
        panel.setBackground(new Color(51, 0, 0));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(102, 0, 0));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGestionarPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGestionarPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGestionarPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGestionarPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGestionarPagos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnActualizar;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnCancelarPago;
    private javax.swing.JPanel btnCerrarCaja;
    private javax.swing.JPanel btnMini;
    private javax.swing.JPanel btnMostrarServiciosActivos;
    private javax.swing.JPanel btnNuevaSolicitud1;
    private javax.swing.JPanel btnNuevaSolicitud3;
    private javax.swing.JPanel btnNuevaSolicitud4;
    private javax.swing.JPanel btnNuevaSolicitud5;
    private javax.swing.JPanel btnNuevaSolicitud6;
    private javax.swing.JPanel btnRealizarPago;
    private javax.swing.JPanel btnReportes;
    private javax.swing.JPanel btnRevisarPagos;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JPanel btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAceptado;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadodeCaja;
    private javax.swing.JLabel lblMini;
    private javax.swing.JLabel lblrevertir;
    private javax.swing.JPanel mover;
    private javax.swing.JTable tblPagos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
