/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Clientes;

import Datos.DPersona;
import Datos.DServiciodelCliente;
import Datos.DSolicitud;
import Datos.DTrabajos;
import Logica.ConexionSingleton;
import Logica.LSolicitud;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author josug
 */
public class frmPrincipalSolicitudesNuevo extends javax.swing.JFrame {

    public int xx;
    public int xy;
    Connection cn = ConexionSingleton.getConnection();
    public int control = 0;
    public static String accion;
    public static String eliminar = null;
    public static String editar = null;
    
    public static int id;
    public static String ids;
    public static String nombre;
    public static String apellido;
    public static String cedulaIdent;
    public static String fechaSolicitud;
    public static int idServicio;
    public static String nombreServicio;
    public static String estado;
    public static String telefono;
    public static String RUC;
    public static int idBarrio;
    public static String barrio;
    public static int idDireccion;
    public static String direccion;
    
    public static int idPersona;
    public static int idSolicitud;
    public static int idServicioC;
    
    LSolicitud ls = new LSolicitud();
    

    /**
     * Creates new form frmPrincipalSolicitudesNuevo
     */
    public frmPrincipalSolicitudesNuevo() {
        initComponents();
        lblrevertir.setVisible(false);
        mostrarBuscar("");
        this.setLocationRelativeTo(null);
        ordenarTamaños();
        btnBuscar.setEnabled(false);
    }

    public void ordenarTamaños() {
        TableColumnModel Modelo = tblSolicitudes.getColumnModel();
        Modelo.getColumn(0).setPreferredWidth(15);
        Modelo.getColumn(0).setResizable(false);
        Modelo.getColumn(1).setPreferredWidth(75);
        Modelo.getColumn(1).setResizable(false);
        Modelo.getColumn(2).setPreferredWidth(75);
        Modelo.getColumn(2).setResizable(false);
        Modelo.getColumn(3).setPreferredWidth(60);
        Modelo.getColumn(3).setResizable(false);
        Modelo.getColumn(4).setPreferredWidth(100);
        Modelo.getColumn(4).setResizable(false);
        Modelo.getColumn(5).setPreferredWidth(95);
        Modelo.getColumn(5).setResizable(false);
        Modelo.getColumn(6).setPreferredWidth(15);
        Modelo.getColumn(6).setResizable(false);
        Modelo.getColumn(7).setPreferredWidth(90);
        Modelo.getColumn(7).setResizable(false);
    }

    public void mostrarBuscar(String buscar) {
        try {
            DefaultTableModel miModelo;
            LSolicitud log = new LSolicitud();
            miModelo = log.mostrarSolicitud(buscar);
            tblSolicitudes.setModel(miModelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void mostrarBuscarActivo(String buscar) {
        try {
            DefaultTableModel miModelo;
            LSolicitud log = new LSolicitud();
            miModelo = log.mostrarSolicitudesAceptada(buscar);
            tblSolicitudes.setModel(miModelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator8 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnNuevaSolicitud = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        btnEditarSolicitud = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        btnEliminarSolicitud = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnNuevaSolicitudFondo = new javax.swing.JPanel();
        btnEliminarSolicitudFondo = new javax.swing.JPanel();
        btnVolveralMenuFondo = new javax.swing.JPanel();
        btnEditarSolicitudFondo = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        btnActualizarFondo = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        btnReportes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSolicitudes = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        btnMostrarServiciosActivos = new javax.swing.JPanel();
        lblrevertir = new javax.swing.JLabel();
        lblAceptado = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDeshacer = new javax.swing.JPanel();
        lblDeshacer = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        mover = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        btnMini = new javax.swing.JPanel();
        lblMini = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevaSolicitud.setBackground(new java.awt.Color(102, 0, 0));
        btnNuevaSolicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitudFocusGained(evt);
            }
        });
        btnNuevaSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitudMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitudMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitudMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitudMouseReleased(evt);
            }
        });
        btnNuevaSolicitud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_plus_math_30px_1.png"))); // NOI18N
        btnNuevaSolicitud.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 31, 36));
        btnNuevaSolicitud.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 37, 171, 10));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Nueva Solicitud");
        btnNuevaSolicitud.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel2.add(btnNuevaSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, 50));

        btnEditarSolicitud.setBackground(new java.awt.Color(102, 0, 0));
        btnEditarSolicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditarSolicitud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditarSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarSolicitudMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarSolicitudMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarSolicitudMousePressed(evt);
            }
        });
        btnEditarSolicitud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_edit_30px.png"))); // NOI18N
        btnEditarSolicitud.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 31, 36));
        btnEditarSolicitud.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 37, 171, 10));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Editar Solicitud");
        btnEditarSolicitud.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel2.add(btnEditarSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 240, 50));

        btnEliminarSolicitud.setBackground(new java.awt.Color(102, 0, 0));
        btnEliminarSolicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarSolicitud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminarSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarSolicitudMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarSolicitudMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarSolicitudMousePressed(evt);
            }
        });
        btnEliminarSolicitud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_trash_30px.png"))); // NOI18N
        btnEliminarSolicitud.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 31, 36));
        btnEliminarSolicitud.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 37, 171, 10));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Eliminar Solicitud");
        btnEliminarSolicitud.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel2.add(btnEliminarSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 240, 50));

        btnVolver.setBackground(new java.awt.Color(102, 0, 0));
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVolverMousePressed(evt);
            }
        });
        btnVolver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_back_30px.png"))); // NOI18N
        btnVolver.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 31, 36));
        btnVolver.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 37, 170, 10));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Volver al Menu");
        btnVolver.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 240, 50));

        jLabel17.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("JOTZPOT");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnNuevaSolicitudFondo.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaSolicitudFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitudFondo.setEnabled(false);
        btnNuevaSolicitudFondo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitudFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitudFondoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitudFondoLayout = new javax.swing.GroupLayout(btnNuevaSolicitudFondo);
        btnNuevaSolicitudFondo.setLayout(btnNuevaSolicitudFondoLayout);
        btnNuevaSolicitudFondoLayout.setHorizontalGroup(
            btnNuevaSolicitudFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnNuevaSolicitudFondoLayout.setVerticalGroup(
            btnNuevaSolicitudFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnNuevaSolicitudFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 240, 50));

        btnEliminarSolicitudFondo.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminarSolicitudFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarSolicitudFondo.setEnabled(false);
        btnEliminarSolicitudFondo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminarSolicitudFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarSolicitudFondoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnEliminarSolicitudFondoLayout = new javax.swing.GroupLayout(btnEliminarSolicitudFondo);
        btnEliminarSolicitudFondo.setLayout(btnEliminarSolicitudFondoLayout);
        btnEliminarSolicitudFondoLayout.setHorizontalGroup(
            btnEliminarSolicitudFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnEliminarSolicitudFondoLayout.setVerticalGroup(
            btnEliminarSolicitudFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnEliminarSolicitudFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 50));

        btnVolveralMenuFondo.setBackground(new java.awt.Color(0, 0, 0));
        btnVolveralMenuFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolveralMenuFondo.setEnabled(false);
        btnVolveralMenuFondo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVolveralMenuFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVolveralMenuFondoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnVolveralMenuFondoLayout = new javax.swing.GroupLayout(btnVolveralMenuFondo);
        btnVolveralMenuFondo.setLayout(btnVolveralMenuFondoLayout);
        btnVolveralMenuFondoLayout.setHorizontalGroup(
            btnVolveralMenuFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnVolveralMenuFondoLayout.setVerticalGroup(
            btnVolveralMenuFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnVolveralMenuFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 240, 50));

        btnEditarSolicitudFondo.setBackground(new java.awt.Color(0, 0, 0));
        btnEditarSolicitudFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditarSolicitudFondo.setEnabled(false);
        btnEditarSolicitudFondo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditarSolicitudFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarSolicitudFondoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnEditarSolicitudFondoLayout = new javax.swing.GroupLayout(btnEditarSolicitudFondo);
        btnEditarSolicitudFondo.setLayout(btnEditarSolicitudFondoLayout);
        btnEditarSolicitudFondoLayout.setHorizontalGroup(
            btnEditarSolicitudFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnEditarSolicitudFondoLayout.setVerticalGroup(
            btnEditarSolicitudFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnEditarSolicitudFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 240, 50));

        btnActualizar.setBackground(new java.awt.Color(102, 0, 0));
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnActualizarMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarMouseEntered(evt);
            }
        });
        btnActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_exit_30px.png"))); // NOI18N
        btnActualizar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 31, 36));
        btnActualizar.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 37, 170, 10));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Actualizar");
        btnActualizar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 240, 50));

        btnActualizarFondo.setBackground(new java.awt.Color(0, 0, 0));
        btnActualizarFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizarFondo.setEnabled(false);
        btnActualizarFondo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnActualizarFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnActualizarFondoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnActualizarFondoLayout = new javax.swing.GroupLayout(btnActualizarFondo);
        btnActualizarFondo.setLayout(btnActualizarFondoLayout);
        btnActualizarFondoLayout.setHorizontalGroup(
            btnActualizarFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnActualizarFondoLayout.setVerticalGroup(
            btnActualizarFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnActualizarFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 40, 20));
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 40, 10));
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 40, 20));

        jLabel19.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("SOLICITUDES");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 170, 50));

        jLabel20.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("SERVINET");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, -1, -1));

        jLabel21.setFont(new java.awt.Font("Bauhaus 93", 1, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("INTERNET");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 30, 50, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 610));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusqueda.setBackground(new java.awt.Color(204, 204, 204));
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });
        jPanel3.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 32, 160, -1));

        btnReportes.setBackground(new java.awt.Color(102, 0, 0));
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnReportesMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportesMouseEntered(evt);
            }
        });
        btnReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_print_30px.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        btnReportes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 30, 38));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Imprimir Reporte");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel22MousePressed(evt);
            }
        });
        btnReportes.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel3.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 170, 40));

        btnBuscar.setBackground(new java.awt.Color(102, 0, 0));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });
        btnBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_search_30px_1.png"))); // NOI18N
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBuscarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBuscarMouseEntered(evt);
            }
        });
        btnBuscar.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jPanel3.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 50, 50));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 50, 50));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 170, 40));
        jPanel3.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 18, 380, 10));
        jPanel3.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 380, 10));
        jPanel3.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 28, 380, 10));
        jPanel3.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 380, 10));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 920, 80));

        jScrollPane1.setBorder(null);

        tblSolicitudes.setAutoCreateRowSorter(true);
        tblSolicitudes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblSolicitudes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblSolicitudes.setGridColor(new java.awt.Color(255, 255, 255));
        tblSolicitudes.setRowHeight(25);
        tblSolicitudes.setSelectionBackground(new java.awt.Color(153, 0, 0));
        tblSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSolicitudesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSolicitudes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 780, 390));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 10, 200));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 10, 200));

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 10, 200));

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 10, 200));

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 10, 200));

        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 10, 200));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 140, 110, 470));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrarServiciosActivos.setBackground(new java.awt.Color(102, 0, 0));
        btnMostrarServiciosActivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarServiciosActivosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarServiciosActivosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMostrarServiciosActivosMousePressed(evt);
            }
        });
        btnMostrarServiciosActivos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblrevertir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblrevertir.setForeground(new java.awt.Color(204, 204, 204));
        lblrevertir.setText("REVERTIR");
        btnMostrarServiciosActivos.add(lblrevertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        lblAceptado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAceptado.setForeground(new java.awt.Color(204, 204, 204));
        lblAceptado.setText("ESTADO ACEPTADO");
        btnMostrarServiciosActivos.add(lblAceptado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel10.add(btnMostrarServiciosActivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 140, 30));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setEnabled(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 140, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MOSTRAR:");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnDeshacer.setBackground(new java.awt.Color(102, 0, 0));
        btnDeshacer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeshacerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeshacerMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDeshacerMousePressed(evt);
            }
        });
        btnDeshacer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDeshacer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDeshacer.setForeground(new java.awt.Color(204, 204, 204));
        lblDeshacer.setText("DESHACER");
        btnDeshacer.add(lblDeshacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel10.add(btnDeshacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 90, 30));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setEnabled(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 90, 30));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 830, 60));

        mover.setBackground(new java.awt.Color(204, 204, 204));
        mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moverMouseDragged(evt);
            }
        });
        mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moverMousePressed(evt);
            }
        });
        mover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(102, 0, 0));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px.png"))); // NOI18N
        btnSalir.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 20, 20));

        mover.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, 30, 30));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        mover.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 20, 30, 30));

        btnMini.setBackground(new java.awt.Color(102, 0, 0));
        btnMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMiniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMiniMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMiniMousePressed(evt);
            }
        });
        btnMini.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_minimize_window_20px.png"))); // NOI18N
        lblMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMiniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMiniMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMiniMousePressed(evt);
            }
        });
        btnMini.add(lblMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 20, 20));

        mover.add(btnMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 30, 30));

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        mover.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, 30, 30));

        jPanel1.add(mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaSolicitudMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitudMousePressed
        setColor(btnNuevaSolicitud);
        frmValoresSolicitudNuevo form = new frmValoresSolicitudNuevo();
        form.setVisible(true);
        form.toFront();
        control = 1;
    }//GEN-LAST:event_btnNuevaSolicitudMousePressed

    private void btnEditarSolicitudMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarSolicitudMousePressed
        if (tblSolicitudes.getSelectedRows().length > 0) {
            frmValoresSolicitudNuevo form = new frmValoresSolicitudNuevo();
            editar = "si";
            form.jdFechaSolicitud.setVisible(false);
            form.setVisible(true);
            form.toFront();
        }
    }//GEN-LAST:event_btnEditarSolicitudMousePressed

    private void btnEliminarSolicitudMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarSolicitudMousePressed
        eliminar = "si";
        if (!ids.equals("")) {
            int mensaje = JOptionPane.showConfirmDialog(rootPane, "¿Desea eliminar la Solicitud?", "Confirmación", 2);
            if (mensaje == 0) {
                DSolicitud ds = new DSolicitud();
                DPersona dp = new DPersona();
                DServiciodelCliente dsc = new DServiciodelCliente();
                DTrabajos dt = new DTrabajos();
                LSolicitud fun = new LSolicitud();

                ds.setIdSolicitud(Integer.parseInt(ids));
                dp.setIdPersona(Integer.parseInt(ids));
                dsc.setIdServiciodelCliente(Integer.parseInt(ids));

                if (lblAceptado.isVisible()) {
                    System.out.println("Solicitud Pendiente Eliminada");
                    fun.eliminarSolicitudPendiente(ds, dp, dsc);
                } else {
                    System.out.println("Solicitud Aceptada Eliminada");
                    fun.eliminarSolicitudAceptada(ds);
                }

                if (!lblAceptado.isVisible()) {
                    mostrarBuscarActivo("");
                    ordenarTamaños();
                } else {
                    mostrarBuscar("");
                    ordenarTamaños();
                }
            }
        } else {
        }
    }//GEN-LAST:event_btnEliminarSolicitudMousePressed

    private void btnVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMousePressed
        frmPrincipalMenu form = new frmPrincipalMenu();
        form.setVisible(true);
        form.toFront();
        this.dispose();
    }//GEN-LAST:event_btnVolverMousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed

    }//GEN-LAST:event_jPanel1MousePressed

    private void btnNuevaSolicitudMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitudMouseReleased

    }//GEN-LAST:event_btnNuevaSolicitudMouseReleased

    private void btnNuevaSolicitudFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitudFocusGained

    }//GEN-LAST:event_btnNuevaSolicitudFocusGained

    private void btnNuevaSolicitudMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitudMouseEntered
        setColor(btnNuevaSolicitud);
    }//GEN-LAST:event_btnNuevaSolicitudMouseEntered

    private void btnNuevaSolicitudMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitudMouseExited
        resetColor(btnNuevaSolicitud);
    }//GEN-LAST:event_btnNuevaSolicitudMouseExited

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        frmElegirReporteSolicitudes form = new frmElegirReporteSolicitudes();
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_jLabel6MousePressed

    private void btnNuevaSolicitudFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitudFondoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitudFondoMousePressed

    private void btnEliminarSolicitudFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarSolicitudFondoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarSolicitudFondoMousePressed

    private void btnVolveralMenuFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolveralMenuFondoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolveralMenuFondoMousePressed

    private void btnEditarSolicitudFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarSolicitudFondoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarSolicitudFondoMousePressed

    private void btnMostrarServiciosActivosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarServiciosActivosMousePressed
        if (lblAceptado.isVisible()) {
            lblAceptado.setVisible(false);
            lblrevertir.setVisible(true);
            mostrarBuscarActivo("");
            ordenarTamaños();
            btnEditarSolicitud.setVisible(false);
            btnEditarSolicitudFondo.setVisible(false);
        } else {
            lblAceptado.setVisible(true);
            lblrevertir.setVisible(false);
            mostrarBuscar("");
            ordenarTamaños();
            btnEditarSolicitud.setVisible(true);
            btnEditarSolicitudFondo.setVisible(true);
        }
    }//GEN-LAST:event_btnMostrarServiciosActivosMousePressed

    private void btnActualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMousePressed
        Connection cn = ConexionSingleton.getConnection();
        if (!lblAceptado.isVisible()) {
            mostrarBuscarActivo("");
            ordenarTamaños();
        } else {
            mostrarBuscar("");
            ordenarTamaños();
        }
    }//GEN-LAST:event_btnActualizarMousePressed

    private void btnActualizarFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarFondoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarFondoMousePressed

    private void btnReportesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMousePressed
        frmElegirReporteSolicitudes form = new frmElegirReporteSolicitudes();
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_btnReportesMousePressed

    private void btnEditarSolicitudMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarSolicitudMouseEntered
        setColor(btnEditarSolicitud);
    }//GEN-LAST:event_btnEditarSolicitudMouseEntered

    private void btnEditarSolicitudMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarSolicitudMouseExited
        resetColor(btnEditarSolicitud);
    }//GEN-LAST:event_btnEditarSolicitudMouseExited

    private void btnEliminarSolicitudMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarSolicitudMouseEntered
        setColor(btnEliminarSolicitud);
    }//GEN-LAST:event_btnEliminarSolicitudMouseEntered

    private void btnEliminarSolicitudMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarSolicitudMouseExited
        resetColor(btnEliminarSolicitud);
    }//GEN-LAST:event_btnEliminarSolicitudMouseExited

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        setColor(btnVolver);
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        resetColor(btnVolver);
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseEntered
        setColor(btnActualizar);
    }//GEN-LAST:event_btnActualizarMouseEntered

    private void btnActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseExited
        resetColor(btnActualizar);
    }//GEN-LAST:event_btnActualizarMouseExited

    private void tblSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSolicitudesMouseClicked
        int fila = tblSolicitudes.rowAtPoint(evt.getPoint());
        id = Integer.parseInt(tblSolicitudes.getValueAt(fila, 0).toString());
        ids = tblSolicitudes.getValueAt(fila, 0).toString();
        nombre = tblSolicitudes.getValueAt(fila, 1).toString();
        apellido = tblSolicitudes.getValueAt(fila, 2).toString();
        cedulaIdent = tblSolicitudes.getValueAt(fila, 3).toString();
        telefono = ls.traerTelefono(id);
        RUC = ls.traerRUC(id);
        idDireccion = ls.traerIdDireccion(id);
        direccion = ls.traerDireccion(idDireccion);
        idBarrio = ls.traerIdBarrio(idDireccion);
        barrio = ls.traerBarrio(idBarrio);
        fechaSolicitud = tblSolicitudes.getValueAt(fila, 4).toString();
        idServicio = Integer.parseInt(tblSolicitudes.getValueAt(fila, 6).toString());
        nombreServicio = tblSolicitudes.getValueAt(fila, 7).toString();
        estado = tblSolicitudes.getValueAt(fila, 8).toString();
    }//GEN-LAST:event_tblSolicitudesMouseClicked

    private void jLabel22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MousePressed
        frmElegirReporteSolicitudes form = new frmElegirReporteSolicitudes();
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_jLabel22MousePressed

    private void btnMostrarServiciosActivosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarServiciosActivosMouseEntered
        setColor(btnMostrarServiciosActivos);
    }//GEN-LAST:event_btnMostrarServiciosActivosMouseEntered

    private void btnMostrarServiciosActivosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarServiciosActivosMouseExited
        resetColor(btnMostrarServiciosActivos);
    }//GEN-LAST:event_btnMostrarServiciosActivosMouseExited

    private void btnReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseEntered
        setColor(btnReportes);
    }//GEN-LAST:event_btnReportesMouseEntered

    private void btnReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseExited
        resetColor(btnReportes);
    }//GEN-LAST:event_btnReportesMouseExited

    private void lblBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseEntered
        
    }//GEN-LAST:event_lblBuscarMouseEntered

    private void lblBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseExited
        
    }//GEN-LAST:event_lblBuscarMouseExited

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        setColor(btnSalir);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        resetColor(btnSalir);
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        this.dispose();
    }//GEN-LAST:event_btnSalirMousePressed

    private void btnMiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiniMouseEntered
        setColor(btnMini);
    }//GEN-LAST:event_btnMiniMouseEntered

    private void btnMiniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiniMouseExited
        resetColor(btnMini);
    }//GEN-LAST:event_btnMiniMouseExited

    private void moverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_moverMouseDragged

    private void moverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_moverMousePressed

    private void btnDeshacerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeshacerMouseEntered
        setColor(btnDeshacer);
    }//GEN-LAST:event_btnDeshacerMouseEntered

    private void btnDeshacerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeshacerMouseExited
        resetColor(btnDeshacer);
    }//GEN-LAST:event_btnDeshacerMouseExited

    private void btnDeshacerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeshacerMousePressed
            if ("si".equals(eliminar)) {
            if (!ids.equals("")) {
                int mensaje = JOptionPane.showConfirmDialog(rootPane, "¿Desea Deshacer el ultimo eliminado?", "Confirmación", 2);
                if (mensaje == 0) {
                    DSolicitud ds = new DSolicitud();
                    DPersona dp = new DPersona();
                    DServiciodelCliente dsc = new DServiciodelCliente();
                    DTrabajos dt = new DTrabajos();
                    LSolicitud fun = new LSolicitud();

                    ds.setIdSolicitud(Integer.parseInt(ids));
                    dp.setIdPersona(Integer.parseInt(ids));
                    dsc.setIdServiciodelCliente(Integer.parseInt(ids));

                    if (lblAceptado.isVisible()) {
                        System.out.println("Hecho");
                        fun.DeshacerPendiente(ds, dp, dsc);
                    } else {
                        System.out.println("Hecho");
                        fun.DeshacerActivo(ds);
                    }

                    if (!lblAceptado.isVisible()) {
                        mostrarBuscarActivo("");
                        ordenarTamaños();
                        ids = "";
                    } else {
                        mostrarBuscar("");
                        ordenarTamaños();
                        ids = "";
                    }
                }
            } else {

            }
        } else {
            System.out.println("No se han eliminado registros");
            JOptionPane.showMessageDialog(null, "No se han eliminado recientemente registros");
        }
    }//GEN-LAST:event_btnDeshacerMousePressed

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresa solo el Nro de Cedula");
            txtBusqueda.setText("");
            txtBusqueda.requestFocus();
        }
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        if(!lblAceptado.isVisible()){
            mostrarBuscarActivo(txtBusqueda.getText());
            ordenarTamaños();
        }else {
            mostrarBuscar(txtBusqueda.getText());
            ordenarTamaños();
        }
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void btnMiniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiniMousePressed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMiniMousePressed

    private void lblMiniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMiniMousePressed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMiniMousePressed

    private void lblMiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMiniMouseEntered
        setColor(btnMini);
    }//GEN-LAST:event_lblMiniMouseEntered

    private void lblMiniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMiniMouseExited
        resetColor(btnMini);
    }//GEN-LAST:event_lblMiniMouseExited

    void setColor(JPanel panel) {
        panel.setBackground(new Color(51, 0, 0));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(102, 0, 0));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalSolicitudesNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalSolicitudesNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalSolicitudesNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalSolicitudesNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipalSolicitudesNuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnActualizar;
    private javax.swing.JPanel btnActualizarFondo;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnDeshacer;
    private javax.swing.JPanel btnEditarSolicitud;
    private javax.swing.JPanel btnEditarSolicitudFondo;
    private javax.swing.JPanel btnEliminarSolicitud;
    private javax.swing.JPanel btnEliminarSolicitudFondo;
    private javax.swing.JPanel btnMini;
    private javax.swing.JPanel btnMostrarServiciosActivos;
    public javax.swing.JPanel btnNuevaSolicitud;
    private javax.swing.JPanel btnNuevaSolicitudFondo;
    private javax.swing.JPanel btnReportes;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JPanel btnVolver;
    private javax.swing.JPanel btnVolveralMenuFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAceptado;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblDeshacer;
    private javax.swing.JLabel lblMini;
    private javax.swing.JLabel lblrevertir;
    private javax.swing.JPanel mover;
    private javax.swing.JTable tblSolicitudes;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
