/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Clientes;

import Logica.ConexionSingleton;
import Logica.LSolicitud;
import Presentacion.Cuadrillas.frmMenuCuadrillas;
import Presentacion.Cuadrillas.frmRevisarSolicitudes;
import java.awt.Color;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author josug
 */
public class frmPrincipalMenu extends javax.swing.JFrame {
    public int xx;
    public int xy;
    Connection cn = ConexionSingleton.getConnection();
    public int control = 0;
    /**
     * Creates new form frmPrincipalSolicitudesNuevo
     */
    public frmPrincipalMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    void setColor(JPanel panel) {
        panel.setBackground(new Color(51, 0, 0));
    }

    void resetColorUser(JPanel panel) {
        panel.setBackground(new Color(102, 102, 102));
    }
    
    void resetColor(JPanel panel) {
        panel.setBackground(new Color(102, 0, 0));
    }
    
    void setColorUser(JPanel panel) {
        panel.setBackground(new Color(51, 51, 51));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator39 = new javax.swing.JSeparator();
        jSeparator40 = new javax.swing.JSeparator();
        jSeparator37 = new javax.swing.JSeparator();
        jSeparator38 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator41 = new javax.swing.JSeparator();
        jSeparator42 = new javax.swing.JSeparator();
        jSeparator43 = new javax.swing.JSeparator();
        jSeparator44 = new javax.swing.JSeparator();
        mover = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnNuevaSolicitud = new javax.swing.JPanel();
        lblSolicitudes = new javax.swing.JLabel();
        btnNuevaSolicitud1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRevisarServicios = new javax.swing.JPanel();
        lblServiciosdelCliente = new javax.swing.JLabel();
        btnNuevaSolicitud3 = new javax.swing.JPanel();
        btnRevisarFacturas = new javax.swing.JPanel();
        lblFacturas = new javax.swing.JLabel();
        btnNuevaSolicitud4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnRealizarPagos = new javax.swing.JPanel();
        lblPagos = new javax.swing.JLabel();
        btnNuevaSolicitud6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        btnGestionarCuadrillas = new javax.swing.JPanel();
        lblCuadrillas = new javax.swing.JLabel();
        btnNuevaSolicitud2 = new javax.swing.JPanel();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        jSeparator28 = new javax.swing.JSeparator();
        jSeparator29 = new javax.swing.JSeparator();
        jSeparator30 = new javax.swing.JSeparator();
        jSeparator31 = new javax.swing.JSeparator();
        jSeparator32 = new javax.swing.JSeparator();
        jSeparator33 = new javax.swing.JSeparator();
        jSeparator34 = new javax.swing.JSeparator();
        jSeparator35 = new javax.swing.JSeparator();
        jSeparator36 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUsuario.setBackground(new java.awt.Color(102, 102, 102));
        btnUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsuarioMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsuarioMouseEntered(evt);
            }
        });
        btnUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_user_90px.png"))); // NOI18N
        btnUsuario.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 90));

        lblNombreUsuario.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setText("NOMBRE USUARIO");
        btnUsuario.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jPanel2.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 130, 130));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 130, 130));

        jSeparator39.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 10, 100));
        jPanel2.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 170, 20));
        jPanel2.add(jSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 170, 20));

        jSeparator38.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 10, 100));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dia:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Hora:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 40, 10));
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 40, 10));
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 40, -1));

        jLabel20.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("SERVINET");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 550));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 760, 10));
        jPanel3.add(jSeparator42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 760, 10));
        jPanel3.add(jSeparator43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 28, 760, 10));
        jPanel3.add(jSeparator44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 18, 760, 10));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 800, 80));

        mover.setBackground(new java.awt.Color(204, 204, 204));
        mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moverMouseDragged(evt);
            }
        });
        mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moverMousePressed(evt);
            }
        });
        mover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 40));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevaSolicitud.setBackground(new java.awt.Color(102, 0, 0));
        btnNuevaSolicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitudFocusGained(evt);
            }
        });
        btnNuevaSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitudMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitudMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitudMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitudMouseEntered(evt);
            }
        });
        btnNuevaSolicitud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSolicitudes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_pencil_100px_3.png"))); // NOI18N
        lblSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSolicitudesMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSolicitudesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSolicitudesMouseEntered(evt);
            }
        });
        btnNuevaSolicitud.add(lblSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jPanel4.add(btnNuevaSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 120, 120));

        btnNuevaSolicitud1.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaSolicitud1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitud1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitud1FocusGained(evt);
            }
        });
        btnNuevaSolicitud1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud1MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitud1Layout = new javax.swing.GroupLayout(btnNuevaSolicitud1);
        btnNuevaSolicitud1.setLayout(btnNuevaSolicitud1Layout);
        btnNuevaSolicitud1Layout.setHorizontalGroup(
            btnNuevaSolicitud1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        btnNuevaSolicitud1Layout.setVerticalGroup(
            btnNuevaSolicitud1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel4.add(btnNuevaSolicitud1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 120, 120));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setText("REALIZAR PAGOS");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, -1, -1));

        btnRevisarServicios.setBackground(new java.awt.Color(102, 0, 0));
        btnRevisarServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRevisarServicios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRevisarServicios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnRevisarServiciosFocusGained(evt);
            }
        });
        btnRevisarServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRevisarServiciosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRevisarServiciosMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRevisarServiciosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRevisarServiciosMouseEntered(evt);
            }
        });
        btnRevisarServicios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblServiciosdelCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_check_document_100px.png"))); // NOI18N
        lblServiciosdelCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblServiciosdelClienteMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblServiciosdelClienteMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblServiciosdelClienteMouseEntered(evt);
            }
        });
        btnRevisarServicios.add(lblServiciosdelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jPanel4.add(btnRevisarServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 120, 120));

        btnNuevaSolicitud3.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaSolicitud3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitud3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitud3FocusGained(evt);
            }
        });
        btnNuevaSolicitud3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud3MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud3MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitud3Layout = new javax.swing.GroupLayout(btnNuevaSolicitud3);
        btnNuevaSolicitud3.setLayout(btnNuevaSolicitud3Layout);
        btnNuevaSolicitud3Layout.setHorizontalGroup(
            btnNuevaSolicitud3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        btnNuevaSolicitud3Layout.setVerticalGroup(
            btnNuevaSolicitud3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel4.add(btnNuevaSolicitud3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 120, 120));

        btnRevisarFacturas.setBackground(new java.awt.Color(102, 0, 0));
        btnRevisarFacturas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRevisarFacturas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRevisarFacturas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnRevisarFacturasFocusGained(evt);
            }
        });
        btnRevisarFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRevisarFacturasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRevisarFacturasMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRevisarFacturasMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRevisarFacturasMouseEntered(evt);
            }
        });
        btnRevisarFacturas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_credit_control_100px.png"))); // NOI18N
        lblFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblFacturasMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFacturasMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFacturasMouseEntered(evt);
            }
        });
        btnRevisarFacturas.add(lblFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jPanel4.add(btnRevisarFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 120, 120));

        btnNuevaSolicitud4.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaSolicitud4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitud4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitud4FocusGained(evt);
            }
        });
        btnNuevaSolicitud4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud4MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud4MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitud4Layout = new javax.swing.GroupLayout(btnNuevaSolicitud4);
        btnNuevaSolicitud4.setLayout(btnNuevaSolicitud4Layout);
        btnNuevaSolicitud4Layout.setHorizontalGroup(
            btnNuevaSolicitud4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        btnNuevaSolicitud4Layout.setVerticalGroup(
            btnNuevaSolicitud4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel4.add(btnNuevaSolicitud4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 120, 120));

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setText("REVISAR SERVICIOS ");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        btnRealizarPagos.setBackground(new java.awt.Color(102, 0, 0));
        btnRealizarPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRealizarPagos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRealizarPagos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnRealizarPagosFocusGained(evt);
            }
        });
        btnRealizarPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRealizarPagosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRealizarPagosMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRealizarPagosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRealizarPagosMouseEntered(evt);
            }
        });
        btnRealizarPagos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_card_payment_100px.png"))); // NOI18N
        lblPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblPagosMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPagosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPagosMouseEntered(evt);
            }
        });
        btnRealizarPagos.add(lblPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jPanel4.add(btnRealizarPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 120, 120));

        btnNuevaSolicitud6.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaSolicitud6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitud6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitud6FocusGained(evt);
            }
        });
        btnNuevaSolicitud6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud6MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud6MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud6MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitud6Layout = new javax.swing.GroupLayout(btnNuevaSolicitud6);
        btnNuevaSolicitud6.setLayout(btnNuevaSolicitud6Layout);
        btnNuevaSolicitud6Layout.setHorizontalGroup(
            btnNuevaSolicitud6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        btnNuevaSolicitud6Layout.setVerticalGroup(
            btnNuevaSolicitud6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel4.add(btnNuevaSolicitud6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 120, 120));

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setText("REVISAR FACTURAS");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 780, -1));

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setText("Gestionar Cuadrillas");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        btnGestionarCuadrillas.setBackground(new java.awt.Color(102, 0, 0));
        btnGestionarCuadrillas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGestionarCuadrillas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGestionarCuadrillas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnGestionarCuadrillasFocusGained(evt);
            }
        });
        btnGestionarCuadrillas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGestionarCuadrillasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnGestionarCuadrillasMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionarCuadrillasMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionarCuadrillasMouseEntered(evt);
            }
        });
        btnGestionarCuadrillas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCuadrillas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_safety_hat_100px.png"))); // NOI18N
        lblCuadrillas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCuadrillasMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCuadrillasMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCuadrillasMouseEntered(evt);
            }
        });
        btnGestionarCuadrillas.add(lblCuadrillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel4.add(btnGestionarCuadrillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 120, 120));

        btnNuevaSolicitud2.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaSolicitud2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitud2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitud2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnNuevaSolicitud2FocusGained(evt);
            }
        });
        btnNuevaSolicitud2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud2MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitud2MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitud2Layout = new javax.swing.GroupLayout(btnNuevaSolicitud2);
        btnNuevaSolicitud2.setLayout(btnNuevaSolicitud2Layout);
        btnNuevaSolicitud2Layout.setHorizontalGroup(
            btnNuevaSolicitud2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        btnNuevaSolicitud2Layout.setVerticalGroup(
            btnNuevaSolicitud2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel4.add(btnNuevaSolicitud2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 120, 120));

        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 10, 170));
        jPanel4.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 170, 20));
        jPanel4.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 170, 20));

        jSeparator20.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 10, 170));
        jPanel4.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 20));

        jSeparator22.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 10, 170));

        jSeparator23.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 10, 170));
        jPanel4.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 170, 20));
        jPanel4.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 170, 20));

        jSeparator26.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 10, 170));

        jSeparator27.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 10, 170));
        jPanel4.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 170, 20));
        jPanel4.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 170, 20));

        jSeparator30.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 10, 170));

        jSeparator31.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 10, 170));
        jPanel4.add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 170, 20));
        jPanel4.add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 170, 20));

        jSeparator34.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 10, 170));

        jSeparator35.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 10, 170));
        jPanel4.add(jSeparator36, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 170, 20));

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setText("SOLICITUDES");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 800, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaSolicitudMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitudMousePressed
        frmPrincipalSolicitudesNuevo form = new frmPrincipalSolicitudesNuevo();
        form.setVisible(true);
        form.toFront();
        this.dispose();
    }//GEN-LAST:event_btnNuevaSolicitudMousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        
    }//GEN-LAST:event_jPanel1MousePressed

    private void moverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_moverMouseDragged

    private void moverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMousePressed
        xx = evt.getX();
         xy = evt.getY();
    }//GEN-LAST:event_moverMousePressed

    private void btnNuevaSolicitudMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitudMouseReleased
       
    }//GEN-LAST:event_btnNuevaSolicitudMouseReleased

    private void btnNuevaSolicitudFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitudFocusGained
        
    }//GEN-LAST:event_btnNuevaSolicitudFocusGained

    private void btnNuevaSolicitudMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitudMouseEntered
        
    }//GEN-LAST:event_btnNuevaSolicitudMouseEntered

    private void btnNuevaSolicitudMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitudMouseExited
        
    }//GEN-LAST:event_btnNuevaSolicitudMouseExited

    private void btnNuevaSolicitud1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1FocusGained

    private void btnNuevaSolicitud1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1MouseEntered

    private void btnNuevaSolicitud1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1MouseExited

    private void btnNuevaSolicitud1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1MousePressed

    private void btnNuevaSolicitud1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud1MouseReleased

    private void btnRevisarServiciosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnRevisarServiciosFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRevisarServiciosFocusGained

    private void btnRevisarServiciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarServiciosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRevisarServiciosMouseEntered

    private void btnRevisarServiciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarServiciosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRevisarServiciosMouseExited

    private void btnRevisarServiciosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarServiciosMousePressed
        frmGestionarServicios form = new frmGestionarServicios();
        form.setVisible(true);
        form.toFront();
        this.dispose();
    }//GEN-LAST:event_btnRevisarServiciosMousePressed

    private void btnRevisarServiciosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarServiciosMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRevisarServiciosMouseReleased

    private void btnNuevaSolicitud3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud3FocusGained

    private void btnNuevaSolicitud3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud3MouseEntered

    private void btnNuevaSolicitud3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud3MouseExited

    private void btnNuevaSolicitud3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud3MousePressed

    private void btnNuevaSolicitud3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud3MouseReleased

    private void btnNuevaSolicitud4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud4FocusGained

    private void btnNuevaSolicitud4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud4MouseEntered

    private void btnNuevaSolicitud4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud4MouseExited

    private void btnNuevaSolicitud4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud4MousePressed

    private void btnNuevaSolicitud4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud4MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud4MouseReleased

    private void btnRevisarFacturasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnRevisarFacturasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRevisarFacturasFocusGained

    private void btnRevisarFacturasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarFacturasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRevisarFacturasMouseEntered

    private void btnRevisarFacturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarFacturasMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRevisarFacturasMouseExited

    private void btnRevisarFacturasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarFacturasMousePressed
    
    }//GEN-LAST:event_btnRevisarFacturasMousePressed

    private void btnRevisarFacturasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarFacturasMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRevisarFacturasMouseReleased

    private void btnNuevaSolicitud6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud6FocusGained

    private void btnNuevaSolicitud6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud6MouseEntered

    private void btnNuevaSolicitud6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud6MouseExited

    private void btnNuevaSolicitud6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud6MousePressed

    private void btnNuevaSolicitud6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud6MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud6MouseReleased

    private void btnRealizarPagosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnRealizarPagosFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarPagosFocusGained

    private void btnRealizarPagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarPagosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarPagosMouseEntered

    private void btnRealizarPagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarPagosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarPagosMouseExited

    private void btnRealizarPagosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarPagosMousePressed
        String estado = "";
        int id = 0;
        String SQL = "select estado from tblcaja order by idCaja desc limit 1";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            
            while(rs.next()){
                estado = rs.getString("estado");
            }
            if(estado.equals("Abierto")){
                frmGestionarPagos form = new frmGestionarPagos();
                form.setVisible(true);
                form.toFront();
                this.dispose();
            }else{
                frmAbrirCaja form = new frmAbrirCaja();
                form.setVisible(true);
                form.toFront();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnRealizarPagosMousePressed

    private void btnRealizarPagosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarPagosMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarPagosMouseReleased

    private void btnNuevaSolicitud2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud2FocusGained

    private void btnNuevaSolicitud2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud2MouseEntered

    private void btnNuevaSolicitud2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud2MouseExited

    private void btnNuevaSolicitud2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud2MousePressed

    private void btnNuevaSolicitud2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitud2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitud2MouseReleased

    private void btnGestionarCuadrillasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnGestionarCuadrillasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarCuadrillasFocusGained

    private void btnGestionarCuadrillasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarCuadrillasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarCuadrillasMouseEntered

    private void btnGestionarCuadrillasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarCuadrillasMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarCuadrillasMouseExited

    private void btnGestionarCuadrillasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarCuadrillasMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarCuadrillasMousePressed

    private void btnGestionarCuadrillasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarCuadrillasMouseReleased
        frmRevisarSolicitudes form = new frmRevisarSolicitudes();
        form.setVisible(true);
        form.toFront();
        this.dispose();
    }//GEN-LAST:event_btnGestionarCuadrillasMouseReleased

    private void lblCuadrillasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCuadrillasMousePressed
        frmMenuCuadrillas form = new frmMenuCuadrillas();
        form.setVisible(true);
        form.toFront();
        this.dispose();
    }//GEN-LAST:event_lblCuadrillasMousePressed

    private void btnUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioMouseEntered
        setColorUser(btnUsuario);
    }//GEN-LAST:event_btnUsuarioMouseEntered

    private void btnUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioMouseExited
        resetColorUser(btnUsuario);
    }//GEN-LAST:event_btnUsuarioMouseExited

    private void lblSolicitudesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSolicitudesMouseEntered
        setColor(btnNuevaSolicitud);
    }//GEN-LAST:event_lblSolicitudesMouseEntered

    private void lblSolicitudesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSolicitudesMouseExited
        resetColor(btnNuevaSolicitud);
    }//GEN-LAST:event_lblSolicitudesMouseExited

    private void lblServiciosdelClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblServiciosdelClienteMouseEntered
        setColor(btnRevisarServicios);
    }//GEN-LAST:event_lblServiciosdelClienteMouseEntered

    private void lblServiciosdelClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblServiciosdelClienteMouseExited
        resetColor(btnRevisarServicios);
    }//GEN-LAST:event_lblServiciosdelClienteMouseExited

    private void lblFacturasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFacturasMouseEntered
        setColor(btnRevisarFacturas);
    }//GEN-LAST:event_lblFacturasMouseEntered

    private void lblFacturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFacturasMouseExited
        resetColor(btnRevisarFacturas);
    }//GEN-LAST:event_lblFacturasMouseExited

    private void lblPagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPagosMouseEntered
        setColor(btnRealizarPagos);
    }//GEN-LAST:event_lblPagosMouseEntered

    private void lblPagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPagosMouseExited
        resetColor(btnRealizarPagos);
    }//GEN-LAST:event_lblPagosMouseExited

    private void lblCuadrillasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCuadrillasMouseEntered
        setColor(btnGestionarCuadrillas);
    }//GEN-LAST:event_lblCuadrillasMouseEntered

    private void lblCuadrillasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCuadrillasMouseExited
        resetColor(btnGestionarCuadrillas);
    }//GEN-LAST:event_lblCuadrillasMouseExited

    private void lblSolicitudesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSolicitudesMousePressed
        frmPrincipalSolicitudesNuevo form = new frmPrincipalSolicitudesNuevo();
        form.setVisible(true);
        form.toFront();
        this.dispose();
    }//GEN-LAST:event_lblSolicitudesMousePressed

    private void lblServiciosdelClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblServiciosdelClienteMousePressed
        frmGestionarServicios form = new frmGestionarServicios();
        form.setVisible(true);
        form.toFront();
        this.dispose();
    }//GEN-LAST:event_lblServiciosdelClienteMousePressed

    private void lblPagosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPagosMousePressed
        String estado = "";
        int id = 0;
        String SQL = "select estado from tblcaja order by idCaja desc limit 1";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            
            while(rs.next()){
                estado = rs.getString("estado");
            }
            if("Abierta".equals(estado)){
                frmGestionarPagos form = new frmGestionarPagos();
                form.setVisible(true);
                form.toFront();
                this.dispose();
            }else{
                frmAbrirCaja form = new frmAbrirCaja();
                form.setVisible(true);
                form.toFront();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblPagosMousePressed

    private void lblFacturasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFacturasMousePressed
        frmRevisarFacturas form = new frmRevisarFacturas();
        form.setVisible(true);
        form.toFront();
        this.dispose();
    }//GEN-LAST:event_lblFacturasMousePressed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipalMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnGestionarCuadrillas;
    public javax.swing.JPanel btnNuevaSolicitud;
    public javax.swing.JPanel btnNuevaSolicitud1;
    public javax.swing.JPanel btnNuevaSolicitud2;
    public javax.swing.JPanel btnNuevaSolicitud3;
    public javax.swing.JPanel btnNuevaSolicitud4;
    public javax.swing.JPanel btnNuevaSolicitud6;
    public javax.swing.JPanel btnRealizarPagos;
    public javax.swing.JPanel btnRevisarFacturas;
    public javax.swing.JPanel btnRevisarServicios;
    private javax.swing.JPanel btnUsuario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblCuadrillas;
    private javax.swing.JLabel lblFacturas;
    public static javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblPagos;
    private javax.swing.JLabel lblServiciosdelCliente;
    private javax.swing.JLabel lblSolicitudes;
    private javax.swing.JPanel mover;
    // End of variables declaration//GEN-END:variables
}
