/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Clientes;

import Datos.DClientes;
import Datos.DPersona;
import Datos.DServiciodelCliente;
import Datos.DSolicitud;
import Logica.LEstados;
import Logica.LSolicitud;
import Presentacion.Mantenimiento.frmVistaDireccionNuevo;
import Presentacion.Mantenimiento.frmVistaServicioNuevo;
import Presentacion.Mantenimiento.frmVistaZonaNuevo;
import java.awt.Color;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author josug
 */
public class frmValoresSolicitudNuevo extends javax.swing.JFrame {

    public static int control = 0;
    private LEstados es = new LEstados();
    Calendar fecha_actual = new GregorianCalendar();
    SimpleDateFormat sdf2 = new SimpleDateFormat("dd");
    Calendar cal = Calendar.getInstance();

    public static String accion = null;
    public static String ruc = "";
    public static String nombres = "";
    public static String apellidos = "";
    public static String cedula = "";
    public static String telefono = "";
    public static int zonaId = 0;
    public static int direccionId = 0;
    public static String direccion = "";
    public static int tiposervicioId = 0;
    public static int estadoId = 0;
    public static int diasActuales;
    public static int diasdeverdad;
    int mesSiguiente;
    int ultimoDia;
    int faltantes;
    int meses = 12;
    public static int idBarrio = 0;
    public static String barrio = "";
    
    /**
     * Creates new form frmValoresSolicitudNuevo
     */
    public frmValoresSolicitudNuevo() {
        initComponents();
        this.setLocationRelativeTo(null);
        jdFechaSolicitud.setCalendar(fecha_actual);
        txtId.setEditable(false);
        txtIdBarrio.setEditable(false);
        txtIdDireccion.setEditable(false);
        txtIdTipo.setEditable(false);
        txtBarrio.setEditable(false);
        txtDireccion.setEditable(false);
        txtTipoSolicitud.setEditable(false);
    }

    void setColor(JPanel panel) {
        panel.setBackground(new Color(51, 0, 0));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(102, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator23 = new javax.swing.JSeparator();
        bg = new javax.swing.JPanel();
        bar = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRUC = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtBarrio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIdBarrio = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtIdDireccion = new javax.swing.JTextField();
        txtIdTipo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTipoSolicitud = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jdFechaSolicitud = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        btnBuscarBarrio = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnBuscarDireccion = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnBuscarSolicitud = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btnGuardar2 = new javax.swing.JPanel();
        btnGuardar4 = new javax.swing.JPanel();
        btnGuardar5 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnGuardar3 = new javax.swing.JPanel();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        jSeparator28 = new javax.swing.JSeparator();
        jSeparator29 = new javax.swing.JSeparator();
        jSeparator30 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar.setBackground(new java.awt.Color(204, 204, 204));
        bar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bar.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 200, 20));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("INSERTE LOS DATOS DE LA SOLICITUD");
        bar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SERVINET");
        bar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        bg.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 40));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 53, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombres:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, -1, -1));

        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombresKeyReleased(evt);
            }
        });
        jPanel2.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 200, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellidos:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, -1, -1));
        jPanel2.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, 200, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cédula de Identidad:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, -1, -1));
        jPanel2.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 201, 120, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Teléfono:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 239, -1, -1));

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 259, 120, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RUC:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 297, -1, -1));
        jPanel2.add(txtRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 317, 120, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 230, 360));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txtBarrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 230, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Barrio:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel3.add(txtIdBarrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 53, -1));
        jPanel3.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 230, -1));
        jPanel3.add(txtIdDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 53, -1));
        jPanel3.add(txtIdTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 148, 53, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tipo de Solicitud:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, -1, -1));
        jPanel3.add(txtTipoSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 230, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fecha de Solicitud:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 186, -1, -1));

        jdFechaSolicitud.setDateFormatString("yyyy/MM/dd ");
        jPanel3.add(jdFechaSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 206, 150, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dirección:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        btnBuscarBarrio.setBackground(new java.awt.Color(102, 0, 0));
        btnBuscarBarrio.setPreferredSize(new java.awt.Dimension(40, 40));
        btnBuscarBarrio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarBarrioMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarBarrioMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarBarrioMouseEntered(evt);
            }
        });
        btnBuscarBarrio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_search_20px.png"))); // NOI18N
        btnBuscarBarrio.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel3.add(btnBuscarBarrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 40, 40));

        btnBuscarDireccion.setBackground(new java.awt.Color(102, 0, 0));
        btnBuscarDireccion.setPreferredSize(new java.awt.Dimension(40, 40));
        btnBuscarDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarDireccionMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarDireccionMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarDireccionMouseEntered(evt);
            }
        });
        btnBuscarDireccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_search_20px.png"))); // NOI18N
        btnBuscarDireccion.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel3.add(btnBuscarDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 40, 40));

        btnBuscarSolicitud.setBackground(new java.awt.Color(102, 0, 0));
        btnBuscarSolicitud.setPreferredSize(new java.awt.Dimension(40, 40));
        btnBuscarSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarSolicitudMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarSolicitudMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarSolicitudMouseEntered(evt);
            }
        });
        btnBuscarSolicitud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_search_20px.png"))); // NOI18N
        btnBuscarSolicitud.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel3.add(btnBuscarSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, 40));

        btnGuardar2.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardar2.setEnabled(false);

        javax.swing.GroupLayout btnGuardar2Layout = new javax.swing.GroupLayout(btnGuardar2);
        btnGuardar2.setLayout(btnGuardar2Layout);
        btnGuardar2Layout.setHorizontalGroup(
            btnGuardar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        btnGuardar2Layout.setVerticalGroup(
            btnGuardar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(btnGuardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 40, 40));

        btnGuardar4.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardar4.setEnabled(false);

        javax.swing.GroupLayout btnGuardar4Layout = new javax.swing.GroupLayout(btnGuardar4);
        btnGuardar4.setLayout(btnGuardar4Layout);
        btnGuardar4Layout.setHorizontalGroup(
            btnGuardar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        btnGuardar4Layout.setVerticalGroup(
            btnGuardar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(btnGuardar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        btnGuardar5.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardar5.setEnabled(false);

        javax.swing.GroupLayout btnGuardar5Layout = new javax.swing.GroupLayout(btnGuardar5);
        btnGuardar5.setLayout(btnGuardar5Layout);
        btnGuardar5Layout.setHorizontalGroup(
            btnGuardar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        btnGuardar5Layout.setVerticalGroup(
            btnGuardar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(btnGuardar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 400, 250));

        btnGuardar.setBackground(new java.awt.Color(102, 0, 0));
        btnGuardar.setPreferredSize(new java.awt.Dimension(50, 50));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuardarMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
        });
        btnGuardar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_save_30px.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(25, 25));
        btnGuardar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 50, 50));

        btnGuardar1.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardar1.setEnabled(false);

        javax.swing.GroupLayout btnGuardar1Layout = new javax.swing.GroupLayout(btnGuardar1);
        btnGuardar1.setLayout(btnGuardar1Layout);
        btnGuardar1Layout.setHorizontalGroup(
            btnGuardar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        btnGuardar1Layout.setVerticalGroup(
            btnGuardar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, -1, 50));

        btnSalir.setBackground(new java.awt.Color(102, 0, 0));
        btnSalir.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_delete_30px.png"))); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(25, 25));
        btnSalir.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 50, 50));

        btnGuardar3.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardar3.setEnabled(false);

        javax.swing.GroupLayout btnGuardar3Layout = new javax.swing.GroupLayout(btnGuardar3);
        btnGuardar3.setLayout(btnGuardar3Layout);
        btnGuardar3Layout.setHorizontalGroup(
            btnGuardar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        btnGuardar3Layout.setVerticalGroup(
            btnGuardar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnGuardar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 50, 50));
        jPanel1.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 580, 10));
        jPanel1.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 400, 10));
        jPanel1.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 120, 10));

        jSeparator25.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 20, 30));

        jSeparator27.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 20, 30));
        jPanel1.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 270, 20));

        jSeparator29.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 20, 300));

        jSeparator30.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 400));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 760, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        this.dispose();
    }//GEN-LAST:event_btnSalirMousePressed

    private void btnGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMousePressed
        if ("".equals(txtNombres.getText())) {
            txtNombres.requestFocus();
            txtNombres.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Ingrese el nombre");
        } else if ("".equals(txtApellidos.getText())) {
            txtApellidos.requestFocus();
            txtApellidos.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Ingrese el apellido");
        } else if ("".equals(txtCedula.getText())) {
            txtCedula.requestFocus();
            txtCedula.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Ingrese el nro de cedula");
        } else if ("".equals(txtTelefono.getText())) {
            txtTelefono.requestFocus();
            txtTelefono.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Ingrese el nro de telefono");
        } else if ("".equals(txtIdBarrio.getText()) || "".equals(txtBarrio.getText())) {
            txtIdBarrio.setBackground(Color.red);
            txtBarrio.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Ingrese el barrio");
        } else if ("".equals(txtIdDireccion.getText()) || "".equals(txtDireccion.getText())) {
            txtIdDireccion.setBackground(Color.red);
            txtDireccion.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Ingrese la direccion");
        } else if ("".equals(txtIdTipo.getText()) || "".equals(txtTipoSolicitud.getText())) {
            txtIdTipo.setBackground(Color.red);
            txtTipoSolicitud.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Ingrese el tipo de solicitud");
        } else if (txtId.getText().equals("")) {
            nombres = txtNombres.getText();
            apellidos = txtApellidos.getText();
            cedula = txtCedula.getText();
            telefono = txtTelefono.getText();
            zonaId = Integer.parseInt(txtIdBarrio.getText());
            direccionId = Integer.parseInt(txtIdDireccion.getText());
            tiposervicioId = Integer.parseInt(txtIdTipo.getText());
            ruc = txtRUC.getText();

            DClientes dc = new DClientes();
            DPersona dp = new DPersona();
            DSolicitud ds = new DSolicitud();
            LSolicitud fun1 = new LSolicitud();
            DServiciodelCliente dsc = new DServiciodelCliente();

            int a, m, d;
            a = fecha_actual.get(Calendar.YEAR) - 1900;
            m = fecha_actual.get(Calendar.MONTH);
            d = fecha_actual.get(Calendar.DAY_OF_MONTH);
            ds.setFechaSolicitud(new Date(a, m, d));

            //Se Inserta la fecha actual para la fecha de la solicitud
            int año = jdFechaSolicitud.getCalendar().get(Calendar.YEAR);
            int mes = jdFechaSolicitud.getCalendar().get(Calendar.MONTH);
            int dia = jdFechaSolicitud.getCalendar().get(Calendar.DAY_OF_MONTH);
            ds.setFechaSolicitud(new Date((año - 1900), mes, dia));

            //Se inserta la fecha final del mes siguiente para la fecha de pago
            Calendar mesActual = new GregorianCalendar();
            mesActual.set(Calendar.MONTH, Calendar.MONTH);
            mesActual.set(Calendar.DAY_OF_MONTH, mesActual.getActualMaximum(Calendar.DAY_OF_MONTH));
            mesActual.set(Calendar.DATE, mesActual.getActualMaximum(Calendar.DATE));
            diasActuales = Integer.parseInt(sdf2.format(mesActual.getTime()));
            diasdeverdad = diasActuales - 7;

            //PROBANDO
            Calendar mesPrimero = new GregorianCalendar();
            mesPrimero.set(Calendar.DAY_OF_MONTH, mesPrimero.getActualMaximum(Calendar.DAY_OF_MONTH));

            if (diasdeverdad > dia) {
                mesSiguiente = mes;
                ultimoDia = Integer.parseInt(sdf2.format(mesPrimero.getTime()));
                dsc.setFechaPago(new Date(año - 1900, mesSiguiente, ultimoDia));
            } else {
                mesSiguiente = mes + 1;
                ultimoDia = Integer.parseInt(sdf2.format(mesActual.getTime()));
                dsc.setFechaPago(new Date(año - 1900, mesSiguiente, ultimoDia));
            }
            dsc.setFechaInicio(new Date((año - 1900), mes, dia));
            dsc.setDetalleservicioId(Integer.parseInt(txtIdTipo.getText()));
            

            dp.setNombre(nombres);
            dp.setApellido(apellidos);
            dp.setCedulaIdent(cedula);
            dp.setTelefono(telefono);
            dp.setDireccionId(direccionId);
            dc.setRuc(txtRUC.getText());
            ds.setServicioId(tiposervicioId);
            fun1.insertarSolicitud(ds, dp, dc, dsc);
            this.dispose();
        }
        


    }//GEN-LAST:event_btnGuardarMousePressed

    private void btnBuscarBarrioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarBarrioMousePressed
        frmVistaZonaNuevo form = new frmVistaZonaNuevo();
        form.setVisible(true);
        form.toFront();
        control = 2;
    }//GEN-LAST:event_btnBuscarBarrioMousePressed

    private void btnBuscarDireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarDireccionMousePressed
        idBarrio = Integer.parseInt(txtIdBarrio.getText());
        barrio = txtBarrio.getText();
        System.out.println(idBarrio);
        System.out.println(barrio);
        frmVistaDireccionNuevo form = new frmVistaDireccionNuevo();
        form.setVisible(true);
        form.toFront();
        control = 2;
    }//GEN-LAST:event_btnBuscarDireccionMousePressed

    private void btnBuscarSolicitudMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarSolicitudMousePressed
        frmVistaServicioNuevo form = new frmVistaServicioNuevo();
        form.setVisible(true);
        form.toFront();
        control = 1;
    }//GEN-LAST:event_btnBuscarSolicitudMousePressed

    private void btnBuscarBarrioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarBarrioMouseEntered
        setColor(btnBuscarBarrio);
    }//GEN-LAST:event_btnBuscarBarrioMouseEntered

    private void btnBuscarBarrioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarBarrioMouseExited
        resetColor(btnBuscarBarrio);
    }//GEN-LAST:event_btnBuscarBarrioMouseExited

    private void btnBuscarDireccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarDireccionMouseEntered
        setColor(btnBuscarDireccion);
    }//GEN-LAST:event_btnBuscarDireccionMouseEntered

    private void btnBuscarDireccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarDireccionMouseExited
        resetColor(btnBuscarDireccion);
    }//GEN-LAST:event_btnBuscarDireccionMouseExited

    private void btnBuscarSolicitudMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarSolicitudMouseEntered
        setColor(btnBuscarSolicitud);
    }//GEN-LAST:event_btnBuscarSolicitudMouseEntered

    private void btnBuscarSolicitudMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarSolicitudMouseExited
        resetColor(btnBuscarSolicitud);
    }//GEN-LAST:event_btnBuscarSolicitudMouseExited

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        setColor(btnGuardar);
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        resetColor(btnGuardar);
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        setColor(btnSalir);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        resetColor(btnSalir);
    }//GEN-LAST:event_btnSalirMouseExited

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtNombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyReleased
        txtNombres.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtNombresKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmValoresSolicitudNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmValoresSolicitudNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmValoresSolicitudNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmValoresSolicitudNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmValoresSolicitudNuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnBuscarBarrio;
    private javax.swing.JPanel btnBuscarDireccion;
    private javax.swing.JPanel btnBuscarSolicitud;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JPanel btnGuardar1;
    private javax.swing.JPanel btnGuardar2;
    private javax.swing.JPanel btnGuardar3;
    private javax.swing.JPanel btnGuardar4;
    private javax.swing.JPanel btnGuardar5;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator5;
    private com.toedter.calendar.JDateChooser jdFechaSolicitud;
    public static javax.swing.JTextField txtApellidos;
    public static javax.swing.JTextField txtBarrio;
    public static javax.swing.JTextField txtCedula;
    public static javax.swing.JTextField txtDireccion;
    public static javax.swing.JTextField txtId;
    public static javax.swing.JTextField txtIdBarrio;
    public static javax.swing.JTextField txtIdDireccion;
    public static javax.swing.JTextField txtIdTipo;
    public static javax.swing.JTextField txtNombres;
    public static javax.swing.JTextField txtRUC;
    public static javax.swing.JTextField txtTelefono;
    public static javax.swing.JTextField txtTipoSolicitud;
    // End of variables declaration//GEN-END:variables
}
