/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.AtencionalCliente;

import Presentacion.Clientes.*;
import Datos.DClientes;
import Datos.DPersona;
import Datos.DReclamos;
import Datos.DServiciodelCliente;
import Datos.DSolicitud;
import Datos.DTrabajos;
import Datos.DTrabajosSolicitud;
import Logica.ConexionSingleton;
import Logica.LClientes;
import Logica.LSolicitud;
import Logica.LTrabajos;
import java.awt.Color;
import java.io.File;
import java.sql.Connection;
import java.sql.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author josug
 */
public class frmAtenciónalCliente extends javax.swing.JFrame {
    public int xx;
    public int xy;
    Connection cn = ConexionSingleton.getConnection();
    public int control = 0;
    public static String accion;
    
    public static int id;
    public static String nombre;
    public static String apellido;
    public static String cedulaIdent;
    public static int idServicio;
    public static String nombreServicio;
    
    /**
     * Creates new form frmPrincipalSolicitudesNuevo
     */
    public frmAtenciónalCliente() {
        initComponents();
        mostrarCliente("");
        this.setLocationRelativeTo(null);
        ordenarTamaños();
        btnRealizarReclamos.setVisible(false);
        btnReportes.setVisible(false);
        btnReporteSombra.setVisible(false);
        btnMostrar.setVisible(false);
        btnMostrarSombra.setVisible(false);
        lblMostrar.setVisible(false);
        lblrevertir.setVisible(false);
    }
    
    public void ordenarTamaños(){
        TableColumnModel Modelo = tblClientes.getColumnModel();
        Modelo.getColumn(0).setPreferredWidth(15);
        Modelo.getColumn(0).setResizable(false);
        Modelo.getColumn(1).setPreferredWidth(75);
        Modelo.getColumn(1).setResizable(false);
        Modelo.getColumn(2).setPreferredWidth(75);
        Modelo.getColumn(2).setResizable(false);
        Modelo.getColumn(3).setPreferredWidth(60);
        Modelo.getColumn(3).setResizable(false);
        Modelo.getColumn(4).setPreferredWidth(100);
        Modelo.getColumn(4).setResizable(false);
        Modelo.getColumn(5).setPreferredWidth(95);
        Modelo.getColumn(5).setResizable(false);
    }
    
    public void mostrarCliente(String buscar){
        accion = "cliente";
        try {
            DefaultTableModel miModelo;
            LClientes log = new LClientes();
            miModelo = log.mostrarClientes(buscar);
            tblClientes.setModel(miModelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void mostrarBuscarActivo(String buscar){
        accion = "reclamo";
        try {
            DefaultTableModel miModelo;
            LSolicitud log = new LSolicitud();
            miModelo = log.mostrarSolicitudesAceptada(buscar);
            tblClientes.setModel(miModelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void mostrarReclamosPendientes(String buscar){
        try {
            DefaultTableModel miModelo;
            LClientes log = new LClientes();
            miModelo = log.mostrarReclamosPendientes(buscar);
            tblClientes.setModel(miModelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void mostrarReclamosAtendidos(String buscar){
        try {
            DefaultTableModel miModelo;
            LClientes log = new LClientes();
            miModelo = log.mostrarReclamosAtendidos(buscar);
            tblClientes.setModel(miModelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator8 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnRealizarReclamos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblRealizarReclamo = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        btnVolveralMenuFondo = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnAtenderReclamo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblAtenderReclamo = new javax.swing.JLabel();
        btnNuevaSolicitudFondo = new javax.swing.JPanel();
        btnRevisarServicios = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        btnRevisarReclamos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        btnEditarSolicitudFondo = new javax.swing.JPanel();
        btnEditarSolicitudFondo1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        btnReportes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnReporteSombra = new javax.swing.JPanel();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        mover = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        btnMostrar = new javax.swing.JPanel();
        lblrevertir = new javax.swing.JLabel();
        lblAceptado = new javax.swing.JLabel();
        btnMostrarSombra = new javax.swing.JPanel();
        lblMostrar = new javax.swing.JLabel();

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setBackground(new java.awt.Color(102, 0, 0));
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVolverMousePressed(evt);
            }
        });
        btnVolver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_back_30px.png"))); // NOI18N
        btnVolver.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 31, 36));
        btnVolver.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 37, 170, 10));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Volver al Menu");
        btnVolver.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 240, 50));

        jLabel17.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("JOTZPOT");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnRealizarReclamos.setBackground(new java.awt.Color(102, 0, 0));
        btnRealizarReclamos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRealizarReclamos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRealizarReclamos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnRealizarReclamosFocusGained(evt);
            }
        });
        btnRealizarReclamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRealizarReclamosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRealizarReclamosMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRealizarReclamosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRealizarReclamosMouseEntered(evt);
            }
        });
        btnRealizarReclamos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_plus_math_30px_1.png"))); // NOI18N
        btnRealizarReclamos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 31, 36));

        lblRealizarReclamo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRealizarReclamo.setForeground(new java.awt.Color(204, 204, 204));
        lblRealizarReclamo.setText("Realizar Reclamo");
        btnRealizarReclamos.add(lblRealizarReclamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));
        btnRealizarReclamos.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 171, 10));

        jPanel2.add(btnRealizarReclamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, 50));

        btnVolveralMenuFondo.setBackground(new java.awt.Color(0, 0, 0));
        btnVolveralMenuFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolveralMenuFondo.setEnabled(false);
        btnVolveralMenuFondo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVolveralMenuFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVolveralMenuFondoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnVolveralMenuFondoLayout = new javax.swing.GroupLayout(btnVolveralMenuFondo);
        btnVolveralMenuFondo.setLayout(btnVolveralMenuFondoLayout);
        btnVolveralMenuFondoLayout.setHorizontalGroup(
            btnVolveralMenuFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnVolveralMenuFondoLayout.setVerticalGroup(
            btnVolveralMenuFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnVolveralMenuFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 240, 50));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 40, 20));
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 40, 10));
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 40, 20));

        jLabel19.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Atención al Cliente");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 240, 50));

        jLabel20.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("SERVINET");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, -1, -1));

        jLabel21.setFont(new java.awt.Font("Bauhaus 93", 1, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("INTERNET");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 30, 50, -1));

        btnAtenderReclamo.setBackground(new java.awt.Color(102, 0, 0));
        btnAtenderReclamo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAtenderReclamo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAtenderReclamo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnAtenderReclamoFocusGained(evt);
            }
        });
        btnAtenderReclamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAtenderReclamoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAtenderReclamoMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtenderReclamoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtenderReclamoMouseEntered(evt);
            }
        });
        btnAtenderReclamo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_plus_math_30px_1.png"))); // NOI18N
        btnAtenderReclamo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 31, 36));
        btnAtenderReclamo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 171, 10));

        lblAtenderReclamo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAtenderReclamo.setForeground(new java.awt.Color(204, 204, 204));
        lblAtenderReclamo.setText("Atender Reclamo");
        btnAtenderReclamo.add(lblAtenderReclamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel2.add(btnAtenderReclamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, 50));

        btnNuevaSolicitudFondo.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaSolicitudFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaSolicitudFondo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaSolicitudFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaSolicitudFondoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnNuevaSolicitudFondoLayout = new javax.swing.GroupLayout(btnNuevaSolicitudFondo);
        btnNuevaSolicitudFondo.setLayout(btnNuevaSolicitudFondoLayout);
        btnNuevaSolicitudFondoLayout.setHorizontalGroup(
            btnNuevaSolicitudFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnNuevaSolicitudFondoLayout.setVerticalGroup(
            btnNuevaSolicitudFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnNuevaSolicitudFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 240, 50));

        btnRevisarServicios.setBackground(new java.awt.Color(102, 0, 0));
        btnRevisarServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRevisarServicios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRevisarServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRevisarServiciosMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRevisarServiciosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRevisarServiciosMouseEntered(evt);
            }
        });
        btnRevisarServicios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_edit_30px.png"))); // NOI18N
        btnRevisarServicios.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 31, 36));
        btnRevisarServicios.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 37, 171, 10));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Revisar Servicios");
        btnRevisarServicios.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel2.add(btnRevisarServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 240, 50));

        btnRevisarReclamos.setBackground(new java.awt.Color(102, 0, 0));
        btnRevisarReclamos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRevisarReclamos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRevisarReclamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRevisarReclamosMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRevisarReclamosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRevisarReclamosMouseEntered(evt);
            }
        });
        btnRevisarReclamos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_edit_30px.png"))); // NOI18N
        btnRevisarReclamos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 31, 36));
        btnRevisarReclamos.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 37, 171, 10));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Revisar Reclamos");
        btnRevisarReclamos.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel2.add(btnRevisarReclamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 240, 50));

        btnEditarSolicitudFondo.setBackground(new java.awt.Color(0, 0, 0));
        btnEditarSolicitudFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditarSolicitudFondo.setEnabled(false);
        btnEditarSolicitudFondo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditarSolicitudFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarSolicitudFondoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnEditarSolicitudFondoLayout = new javax.swing.GroupLayout(btnEditarSolicitudFondo);
        btnEditarSolicitudFondo.setLayout(btnEditarSolicitudFondoLayout);
        btnEditarSolicitudFondoLayout.setHorizontalGroup(
            btnEditarSolicitudFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnEditarSolicitudFondoLayout.setVerticalGroup(
            btnEditarSolicitudFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnEditarSolicitudFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 240, 50));

        btnEditarSolicitudFondo1.setBackground(new java.awt.Color(0, 0, 0));
        btnEditarSolicitudFondo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditarSolicitudFondo1.setEnabled(false);
        btnEditarSolicitudFondo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditarSolicitudFondo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarSolicitudFondo1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnEditarSolicitudFondo1Layout = new javax.swing.GroupLayout(btnEditarSolicitudFondo1);
        btnEditarSolicitudFondo1.setLayout(btnEditarSolicitudFondo1Layout);
        btnEditarSolicitudFondo1Layout.setHorizontalGroup(
            btnEditarSolicitudFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        btnEditarSolicitudFondo1Layout.setVerticalGroup(
            btnEditarSolicitudFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(btnEditarSolicitudFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 240, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 590));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusqueda.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 32, 160, -1));

        btnReportes.setBackground(new java.awt.Color(102, 0, 0));
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnReportesMousePressed(evt);
            }
        });
        btnReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_print_30px.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        btnReportes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 30, 38));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Imprimir Reporte");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel22MousePressed(evt);
            }
        });
        btnReportes.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel3.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 170, 40));

        jPanel6.setBackground(new java.awt.Color(102, 0, 0));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_search_30px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 50, 50));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 50, 50));

        btnReporteSombra.setBackground(new java.awt.Color(0, 0, 0));
        btnReporteSombra.setEnabled(false);

        javax.swing.GroupLayout btnReporteSombraLayout = new javax.swing.GroupLayout(btnReporteSombra);
        btnReporteSombra.setLayout(btnReporteSombraLayout);
        btnReporteSombraLayout.setHorizontalGroup(
            btnReporteSombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        btnReporteSombraLayout.setVerticalGroup(
            btnReporteSombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(btnReporteSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 170, 40));
        jPanel3.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 18, 380, 10));
        jPanel3.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 380, 10));
        jPanel3.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 28, 380, 10));
        jPanel3.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 380, 10));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 920, 80));

        jScrollPane1.setBorder(null);

        tblClientes.setAutoCreateRowSorter(true);
        tblClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblClientes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblClientes.setGridColor(new java.awt.Color(255, 255, 255));
        tblClientes.setRowHeight(25);
        tblClientes.setSelectionBackground(new java.awt.Color(153, 0, 0));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 780, 390));

        mover.setBackground(new java.awt.Color(204, 204, 204));
        mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moverMouseDragged(evt);
            }
        });
        mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moverMousePressed(evt);
            }
        });
        mover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 40));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 10, 200));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 10, 200));

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 10, 200));

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 10, 200));

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 10, 200));

        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 10, 200));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 120, 110, 470));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrar.setBackground(new java.awt.Color(102, 0, 0));
        btnMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMostrarMousePressed(evt);
            }
        });
        btnMostrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblrevertir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblrevertir.setForeground(new java.awt.Color(204, 204, 204));
        lblrevertir.setText("REVERTIR");
        btnMostrar.add(lblrevertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        lblAceptado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAceptado.setForeground(new java.awt.Color(204, 204, 204));
        lblAceptado.setText("Reclamos Atendidos");
        btnMostrar.add(lblAceptado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel10.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 140, 30));

        btnMostrarSombra.setBackground(new java.awt.Color(0, 0, 0));
        btnMostrarSombra.setEnabled(false);

        javax.swing.GroupLayout btnMostrarSombraLayout = new javax.swing.GroupLayout(btnMostrarSombra);
        btnMostrarSombra.setLayout(btnMostrarSombraLayout);
        btnMostrarSombraLayout.setHorizontalGroup(
            btnMostrarSombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        btnMostrarSombraLayout.setVerticalGroup(
            btnMostrarSombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel10.add(btnMostrarSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 140, 30));

        lblMostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMostrar.setForeground(new java.awt.Color(255, 255, 255));
        lblMostrar.setText("MOSTRAR:");
        jPanel10.add(lblMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 830, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtenderReclamoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtenderReclamoMousePressed
        frmValoresReclamos form = new frmValoresReclamos();
        form.setVisible(true);
        form.toFront();
        control = 1;
    }//GEN-LAST:event_btnAtenderReclamoMousePressed

    private void btnVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMousePressed
        frmPrincipalMenu form = new frmPrincipalMenu();
        form.setVisible(true);
        form.toFront();
        this.dispose();
    }//GEN-LAST:event_btnVolverMousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        
    }//GEN-LAST:event_jPanel1MousePressed

    private void moverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_moverMouseDragged

    private void moverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMousePressed
        xx = evt.getX();
         xy = evt.getY();
    }//GEN-LAST:event_moverMousePressed

    private void btnAtenderReclamoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtenderReclamoMouseReleased
       
    }//GEN-LAST:event_btnAtenderReclamoMouseReleased

    private void btnAtenderReclamoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAtenderReclamoFocusGained
        
    }//GEN-LAST:event_btnAtenderReclamoFocusGained

    private void btnAtenderReclamoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtenderReclamoMouseEntered
        setColor(btnAtenderReclamo);
    }//GEN-LAST:event_btnAtenderReclamoMouseEntered

    private void btnAtenderReclamoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtenderReclamoMouseExited
        resetColor(btnAtenderReclamo);
    }//GEN-LAST:event_btnAtenderReclamoMouseExited

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        frmElegirReporteSolicitudes form = new frmElegirReporteSolicitudes();
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_jLabel6MousePressed

    private void btnNuevaSolicitudFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaSolicitudFondoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSolicitudFondoMousePressed

    private void btnVolveralMenuFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolveralMenuFondoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolveralMenuFondoMousePressed

    private void btnReportesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMousePressed
        frmReportesReclamos form = new frmReportesReclamos();
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_btnReportesMousePressed

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        setColor(btnVolver);
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        resetColor(btnVolver);
    }//GEN-LAST:event_btnVolverMouseExited

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        if(accion == "cliente"){
            int fila = tblClientes.rowAtPoint(evt.getPoint());
            id = Integer.parseInt(tblClientes.getValueAt(fila, 0).toString());
            nombre = tblClientes.getValueAt(fila, 1).toString();
            apellido = tblClientes.getValueAt(fila, 2).toString();
            cedulaIdent = tblClientes.getValueAt(fila, 3).toString();
            idServicio = Integer.parseInt(tblClientes.getValueAt(fila, 4).toString());
            nombreServicio = tblClientes.getValueAt(fila, 5).toString();
        }else if(accion == "reclamo"){
            int fila = tblClientes.rowAtPoint(evt.getPoint());
            id = Integer.parseInt(tblClientes.getValueAt(fila, 0).toString());
        }
    }//GEN-LAST:event_tblClientesMouseClicked

    private void jLabel22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MousePressed
        frmElegirReporteSolicitudes form = new frmElegirReporteSolicitudes();
        form.setVisible(true);
        form.toFront();
    }//GEN-LAST:event_jLabel22MousePressed

    private void btnEditarSolicitudFondo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarSolicitudFondo1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarSolicitudFondo1MousePressed

    private void btnEditarSolicitudFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarSolicitudFondoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarSolicitudFondoMousePressed

    private void btnRevisarReclamosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarReclamosMousePressed
        mostrarReclamosPendientes("");
        btnRealizarReclamos.setVisible(true);
        btnAtenderReclamo.setVisible(false);
        btnReportes.setVisible(true);
        btnReporteSombra.setVisible(true);
        btnMostrar.setVisible(true);
        btnMostrarSombra.setVisible(true);
        lblMostrar.setVisible(true);
    }//GEN-LAST:event_btnRevisarReclamosMousePressed

    private void btnRevisarReclamosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarReclamosMouseExited
        resetColor(btnRevisarReclamos);
    }//GEN-LAST:event_btnRevisarReclamosMouseExited

    private void btnRevisarReclamosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarReclamosMouseEntered
        setColor(btnRevisarReclamos);
    }//GEN-LAST:event_btnRevisarReclamosMouseEntered

    private void btnRealizarReclamosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnRealizarReclamosFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarReclamosFocusGained

    private void btnRealizarReclamosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarReclamosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarReclamosMouseEntered

    private void btnRealizarReclamosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarReclamosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarReclamosMouseExited
 
    private void btnRealizarReclamosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarReclamosMousePressed
        mostrarCliente("");
        btnRealizarReclamos.setVisible(false);
        btnAtenderReclamo.setVisible(true);
        btnReportes.setVisible(false);
        btnReporteSombra.setVisible(false);
        btnMostrar.setVisible(false);
        btnMostrarSombra.setVisible(false);
        lblMostrar.setVisible(false);
    }//GEN-LAST:event_btnRealizarReclamosMousePressed

    private void btnRealizarReclamosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarReclamosMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarReclamosMouseReleased

    private void btnRevisarServiciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarServiciosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRevisarServiciosMouseEntered

    private void btnRevisarServiciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarServiciosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRevisarServiciosMouseExited

    private void btnRevisarServiciosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarServiciosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRevisarServiciosMousePressed

    private void btnMostrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMousePressed
        if(lblAceptado.isVisible()){
            lblAceptado.setVisible(false);
            lblrevertir.setVisible(true);
            mostrarReclamosAtendidos("");
            ordenarTamaños();
        }else{
            lblAceptado.setVisible(true);
            lblrevertir.setVisible(false);
            mostrarReclamosPendientes("");
            ordenarTamaños();
        }
    }//GEN-LAST:event_btnMostrarMousePressed

    void setColor(JPanel panel){
        panel.setBackground(new Color(51,0,0));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(102,0,0));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAtenciónalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAtenciónalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAtenciónalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAtenciónalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAtenciónalCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnAtenderReclamo;
    private javax.swing.JPanel btnEditarSolicitudFondo;
    private javax.swing.JPanel btnEditarSolicitudFondo1;
    private javax.swing.JPanel btnMostrar;
    private javax.swing.JPanel btnMostrarSombra;
    private javax.swing.JPanel btnNuevaSolicitudFondo;
    public javax.swing.JPanel btnRealizarReclamos;
    private javax.swing.JPanel btnReporteSombra;
    private javax.swing.JPanel btnReportes;
    private javax.swing.JPanel btnRevisarReclamos;
    private javax.swing.JPanel btnRevisarServicios;
    private javax.swing.JPanel btnVolver;
    private javax.swing.JPanel btnVolveralMenuFondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAceptado;
    private javax.swing.JLabel lblAtenderReclamo;
    private javax.swing.JLabel lblMostrar;
    private javax.swing.JLabel lblRealizarReclamo;
    private javax.swing.JLabel lblrevertir;
    private javax.swing.JPanel mover;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
